/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.dev_tt.tables.Clue;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClueRecord extends UpdatableRecordImpl<ClueRecord> implements Record9<Integer, Integer, Integer, Integer, Integer, String, String, String, Timestamp> {

    private static final long serialVersionUID = -1523354667;

    /**
     * Setter for <code>dev_tt.clue.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dev_tt.clue.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dev_tt.clue.lang_id</code>.
     */
    public void setLangId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>dev_tt.clue.lang_id</code>.
     */
    public Integer getLangId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>dev_tt.clue.scene_id</code>.
     */
    public void setSceneId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>dev_tt.clue.scene_id</code>.
     */
    public Integer getSceneId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>dev_tt.clue.phrase_id</code>.
     */
    public void setPhraseId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>dev_tt.clue.phrase_id</code>.
     */
    public Integer getPhraseId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>dev_tt.clue.parent_id</code>.
     */
    public void setParentId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>dev_tt.clue.parent_id</code>.
     */
    public Integer getParentId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>dev_tt.clue.spot_ids</code>.
     */
    public void setSpotIds(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>dev_tt.clue.spot_ids</code>.
     */
    public String getSpotIds() {
        return (String) get(5);
    }

    /**
     * Setter for <code>dev_tt.clue.active</code>.
     */
    public void setActive(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>dev_tt.clue.active</code>.
     */
    public String getActive() {
        return (String) get(6);
    }

    /**
     * Setter for <code>dev_tt.clue.reviewed</code>.
     */
    public void setReviewed(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>dev_tt.clue.reviewed</code>.
     */
    public String getReviewed() {
        return (String) get(7);
    }

    /**
     * Setter for <code>dev_tt.clue.last_mod</code>.
     */
    public void setLastMod(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>dev_tt.clue.last_mod</code>.
     */
    public Timestamp getLastMod() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, Integer, Integer, String, String, String, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, Integer, Integer, String, String, String, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Clue.CLUE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Clue.CLUE.LANG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Clue.CLUE.SCENE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Clue.CLUE.PHRASE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Clue.CLUE.PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Clue.CLUE.SPOT_IDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Clue.CLUE.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Clue.CLUE.REVIEWED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Clue.CLUE.LAST_MOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getLangId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getSceneId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getPhraseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getSpotIds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getReviewed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLangId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getSceneId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getPhraseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSpotIds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getReviewed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClueRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClueRecord value2(Integer value) {
        setLangId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClueRecord value3(Integer value) {
        setSceneId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClueRecord value4(Integer value) {
        setPhraseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClueRecord value5(Integer value) {
        setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClueRecord value6(String value) {
        setSpotIds(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClueRecord value7(String value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClueRecord value8(String value) {
        setReviewed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClueRecord value9(Timestamp value) {
        setLastMod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClueRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, String value6, String value7, String value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClueRecord
     */
    public ClueRecord() {
        super(Clue.CLUE);
    }

    /**
     * Create a detached, initialised ClueRecord
     */
    public ClueRecord(Integer id, Integer langId, Integer sceneId, Integer phraseId, Integer parentId, String spotIds, String active, String reviewed, Timestamp lastMod) {
        super(Clue.CLUE);

        set(0, id);
        set(1, langId);
        set(2, sceneId);
        set(3, phraseId);
        set(4, parentId);
        set(5, spotIds);
        set(6, active);
        set(7, reviewed);
        set(8, lastMod);
    }
}
