/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.dev_tt.tables.ClueRank;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClueRankRecord extends TableRecordImpl<ClueRankRecord> implements Record8<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Timestamp> {

    private static final long serialVersionUID = 1646987354;

    /**
     * Setter for <code>dev_tt.clue_rank.clue_id</code>.
     */
    public void setClueId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dev_tt.clue_rank.clue_id</code>.
     */
    public Integer getClueId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dev_tt.clue_rank.lang_id</code>.
     */
    public void setLangId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>dev_tt.clue_rank.lang_id</code>.
     */
    public Integer getLangId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>dev_tt.clue_rank.scene_id</code>.
     */
    public void setSceneId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>dev_tt.clue_rank.scene_id</code>.
     */
    public Integer getSceneId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>dev_tt.clue_rank.difficulty</code>.
     */
    public void setDifficulty(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>dev_tt.clue_rank.difficulty</code>.
     */
    public Integer getDifficulty() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>dev_tt.clue_rank.rank</code>.
     */
    public void setRank(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>dev_tt.clue_rank.rank</code>.
     */
    public Integer getRank() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>dev_tt.clue_rank.right</code>.
     */
    public void setRight(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>dev_tt.clue_rank.right</code>.
     */
    public Integer getRight() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>dev_tt.clue_rank.wrong</code>.
     */
    public void setWrong(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>dev_tt.clue_rank.wrong</code>.
     */
    public Integer getWrong() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>dev_tt.clue_rank.last_mod</code>.
     */
    public void setLastMod(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>dev_tt.clue_rank.last_mod</code>.
     */
    public Timestamp getLastMod() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ClueRank.CLUE_RANK.CLUE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ClueRank.CLUE_RANK.LANG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return ClueRank.CLUE_RANK.SCENE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return ClueRank.CLUE_RANK.DIFFICULTY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return ClueRank.CLUE_RANK.RANK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return ClueRank.CLUE_RANK.RIGHT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return ClueRank.CLUE_RANK.WRONG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return ClueRank.CLUE_RANK.LAST_MOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getClueId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getLangId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getSceneId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getDifficulty();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getRank();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getRight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getWrong();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getClueId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLangId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getSceneId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getDifficulty();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getRank();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getRight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getWrong();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClueRankRecord value1(Integer value) {
        setClueId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClueRankRecord value2(Integer value) {
        setLangId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClueRankRecord value3(Integer value) {
        setSceneId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClueRankRecord value4(Integer value) {
        setDifficulty(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClueRankRecord value5(Integer value) {
        setRank(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClueRankRecord value6(Integer value) {
        setRight(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClueRankRecord value7(Integer value) {
        setWrong(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClueRankRecord value8(Timestamp value) {
        setLastMod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClueRankRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Integer value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClueRankRecord
     */
    public ClueRankRecord() {
        super(ClueRank.CLUE_RANK);
    }

    /**
     * Create a detached, initialised ClueRankRecord
     */
    public ClueRankRecord(Integer clueId, Integer langId, Integer sceneId, Integer difficulty, Integer rank, Integer right, Integer wrong, Timestamp lastMod) {
        super(ClueRank.CLUE_RANK);

        set(0, clueId);
        set(1, langId);
        set(2, sceneId);
        set(3, difficulty);
        set(4, rank);
        set(5, right);
        set(6, wrong);
        set(7, lastMod);
    }
}
