/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.dev_tt.tables.Item;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemRecord extends UpdatableRecordImpl<ItemRecord> implements Record11<Integer, Integer, String, String, Integer, Integer, Double, Integer, Integer, String, Timestamp> {

    private static final long serialVersionUID = 759024504;

    /**
     * Setter for <code>dev_tt.item.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dev_tt.item.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dev_tt.item.scene_id</code>.
     */
    public void setSceneId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>dev_tt.item.scene_id</code>.
     */
    public Integer getSceneId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>dev_tt.item.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>dev_tt.item.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>dev_tt.item.acquirable</code>.
     */
    public void setAcquirable(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>dev_tt.item.acquirable</code>.
     */
    public String getAcquirable() {
        return (String) get(3);
    }

    /**
     * Setter for <code>dev_tt.item.phrase_id</code>.
     */
    public void setPhraseId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>dev_tt.item.phrase_id</code>.
     */
    public Integer getPhraseId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>dev_tt.item.xp_threshold</code>.
     */
    public void setXpThreshold(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>dev_tt.item.xp_threshold</code>.
     */
    public Integer getXpThreshold() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>dev_tt.item.probability</code>.
     */
    public void setProbability(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>dev_tt.item.probability</code>.
     */
    public Double getProbability() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>dev_tt.item.cost</code>.
     */
    public void setCost(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>dev_tt.item.cost</code>.
     */
    public Integer getCost() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>dev_tt.item.rarity</code>.
     */
    public void setRarity(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>dev_tt.item.rarity</code>.
     */
    public Integer getRarity() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>dev_tt.item.active</code>.
     */
    public void setActive(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>dev_tt.item.active</code>.
     */
    public String getActive() {
        return (String) get(9);
    }

    /**
     * Setter for <code>dev_tt.item.last_mod</code>.
     */
    public void setLastMod(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>dev_tt.item.last_mod</code>.
     */
    public Timestamp getLastMod() {
        return (Timestamp) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, Integer, String, String, Integer, Integer, Double, Integer, Integer, String, Timestamp> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, Integer, String, String, Integer, Integer, Double, Integer, Integer, String, Timestamp> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Item.ITEM.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Item.ITEM.SCENE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Item.ITEM.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Item.ITEM.ACQUIRABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Item.ITEM.PHRASE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Item.ITEM.XP_THRESHOLD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field7() {
        return Item.ITEM.PROBABILITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Item.ITEM.COST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Item.ITEM.RARITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Item.ITEM.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return Item.ITEM.LAST_MOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getSceneId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getAcquirable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getPhraseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getXpThreshold();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component7() {
        return getProbability();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getCost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getRarity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSceneId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAcquirable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getPhraseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getXpThreshold();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value7() {
        return getProbability();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getCost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getRarity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemRecord value2(Integer value) {
        setSceneId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemRecord value3(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemRecord value4(String value) {
        setAcquirable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemRecord value5(Integer value) {
        setPhraseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemRecord value6(Integer value) {
        setXpThreshold(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemRecord value7(Double value) {
        setProbability(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemRecord value8(Integer value) {
        setCost(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemRecord value9(Integer value) {
        setRarity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemRecord value10(String value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemRecord value11(Timestamp value) {
        setLastMod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemRecord values(Integer value1, Integer value2, String value3, String value4, Integer value5, Integer value6, Double value7, Integer value8, Integer value9, String value10, Timestamp value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemRecord
     */
    public ItemRecord() {
        super(Item.ITEM);
    }

    /**
     * Create a detached, initialised ItemRecord
     */
    public ItemRecord(Integer id, Integer sceneId, String type, String acquirable, Integer phraseId, Integer xpThreshold, Double probability, Integer cost, Integer rarity, String active, Timestamp lastMod) {
        super(Item.ITEM);

        set(0, id);
        set(1, sceneId);
        set(2, type);
        set(3, acquirable);
        set(4, phraseId);
        set(5, xpThreshold);
        set(6, probability);
        set(7, cost);
        set(8, rarity);
        set(9, active);
        set(10, lastMod);
    }
}
