/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.dev_tt.tables.LangScene;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LangSceneRecord extends TableRecordImpl<LangSceneRecord> implements Record5<Integer, Integer, Integer, Integer, Timestamp> {

    private static final long serialVersionUID = -303599637;

    /**
     * Setter for <code>dev_tt.lang_scene.lang_id</code>.
     */
    public void setLangId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dev_tt.lang_scene.lang_id</code>.
     */
    public Integer getLangId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dev_tt.lang_scene.scene_id</code>.
     */
    public void setSceneId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>dev_tt.lang_scene.scene_id</code>.
     */
    public Integer getSceneId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>dev_tt.lang_scene.max_tokens</code>.
     */
    public void setMaxTokens(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>dev_tt.lang_scene.max_tokens</code>.
     */
    public Integer getMaxTokens() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>dev_tt.lang_scene.ranked_clues</code>.
     */
    public void setRankedClues(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>dev_tt.lang_scene.ranked_clues</code>.
     */
    public Integer getRankedClues() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>dev_tt.lang_scene.last_mod</code>.
     */
    public void setLastMod(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>dev_tt.lang_scene.last_mod</code>.
     */
    public Timestamp getLastMod() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Integer, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Integer, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return LangScene.LANG_SCENE.LANG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return LangScene.LANG_SCENE.SCENE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return LangScene.LANG_SCENE.MAX_TOKENS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return LangScene.LANG_SCENE.RANKED_CLUES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return LangScene.LANG_SCENE.LAST_MOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getLangId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getSceneId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getMaxTokens();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getRankedClues();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getLangId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSceneId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getMaxTokens();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getRankedClues();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangSceneRecord value1(Integer value) {
        setLangId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangSceneRecord value2(Integer value) {
        setSceneId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangSceneRecord value3(Integer value) {
        setMaxTokens(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangSceneRecord value4(Integer value) {
        setRankedClues(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangSceneRecord value5(Timestamp value) {
        setLastMod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangSceneRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LangSceneRecord
     */
    public LangSceneRecord() {
        super(LangScene.LANG_SCENE);
    }

    /**
     * Create a detached, initialised LangSceneRecord
     */
    public LangSceneRecord(Integer langId, Integer sceneId, Integer maxTokens, Integer rankedClues, Timestamp lastMod) {
        super(LangScene.LANG_SCENE);

        set(0, langId);
        set(1, sceneId);
        set(2, maxTokens);
        set(3, rankedClues);
        set(4, lastMod);
    }
}
