/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Record2;
import org.jooq.Row10;
import org.jooq.dev_tt.tables.MatchUser;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MatchUserRecord extends UpdatableRecordImpl<MatchUserRecord> implements Record10<Integer, Integer, Integer, Byte, Integer, String, Integer, Integer, Integer, Timestamp> {

    private static final long serialVersionUID = 1302712961;

    /**
     * Setter for <code>dev_tt.match_user.match_id</code>.
     */
    public void setMatchId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dev_tt.match_user.match_id</code>.
     */
    public Integer getMatchId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dev_tt.match_user.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>dev_tt.match_user.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>dev_tt.match_user.opp_id</code>.
     */
    public void setOppId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>dev_tt.match_user.opp_id</code>.
     */
    public Integer getOppId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>dev_tt.match_user.state</code>.
     */
    public void setState(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>dev_tt.match_user.state</code>.
     */
    public Byte getState() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>dev_tt.match_user.xp</code>.
     */
    public void setXp(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>dev_tt.match_user.xp</code>.
     */
    public Integer getXp() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>dev_tt.match_user.results</code>.
     */
    public void setResults(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>dev_tt.match_user.results</code>.
     */
    public String getResults() {
        return (String) get(5);
    }

    /**
     * Setter for <code>dev_tt.match_user.correct_count</code>.
     */
    public void setCorrectCount(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>dev_tt.match_user.correct_count</code>.
     */
    public Integer getCorrectCount() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>dev_tt.match_user.xp_earned</code>.
     */
    public void setXpEarned(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>dev_tt.match_user.xp_earned</code>.
     */
    public Integer getXpEarned() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>dev_tt.match_user.coins_earned</code>.
     */
    public void setCoinsEarned(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>dev_tt.match_user.coins_earned</code>.
     */
    public Integer getCoinsEarned() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>dev_tt.match_user.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>dev_tt.match_user.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Integer, Byte, Integer, String, Integer, Integer, Integer, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Integer, Byte, Integer, String, Integer, Integer, Integer, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MatchUser.MATCH_USER.MATCH_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return MatchUser.MATCH_USER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return MatchUser.MATCH_USER.OPP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return MatchUser.MATCH_USER.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return MatchUser.MATCH_USER.XP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return MatchUser.MATCH_USER.RESULTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return MatchUser.MATCH_USER.CORRECT_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return MatchUser.MATCH_USER.XP_EARNED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return MatchUser.MATCH_USER.COINS_EARNED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return MatchUser.MATCH_USER.CREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getMatchId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getOppId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component4() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getXp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getResults();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getCorrectCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getXpEarned();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getCoinsEarned();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getMatchId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getOppId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getXp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getResults();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getCorrectCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getXpEarned();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getCoinsEarned();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getCreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchUserRecord value1(Integer value) {
        setMatchId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchUserRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchUserRecord value3(Integer value) {
        setOppId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchUserRecord value4(Byte value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchUserRecord value5(Integer value) {
        setXp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchUserRecord value6(String value) {
        setResults(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchUserRecord value7(Integer value) {
        setCorrectCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchUserRecord value8(Integer value) {
        setXpEarned(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchUserRecord value9(Integer value) {
        setCoinsEarned(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchUserRecord value10(Timestamp value) {
        setCreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchUserRecord values(Integer value1, Integer value2, Integer value3, Byte value4, Integer value5, String value6, Integer value7, Integer value8, Integer value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MatchUserRecord
     */
    public MatchUserRecord() {
        super(MatchUser.MATCH_USER);
    }

    /**
     * Create a detached, initialised MatchUserRecord
     */
    public MatchUserRecord(Integer matchId, Integer userId, Integer oppId, Byte state, Integer xp, String results, Integer correctCount, Integer xpEarned, Integer coinsEarned, Timestamp created) {
        super(MatchUser.MATCH_USER);

        set(0, matchId);
        set(1, userId);
        set(2, oppId);
        set(3, state);
        set(4, xp);
        set(5, results);
        set(6, correctCount);
        set(7, xpEarned);
        set(8, coinsEarned);
        set(9, created);
    }
}
