/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.dev_tt.tables.MatchQuestion;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MatchQuestionRecord extends TableRecordImpl<MatchQuestionRecord> implements Record8<Integer, Integer, String, Integer, String, String, String, Timestamp> {

    private static final long serialVersionUID = -1343572439;

    /**
     * Setter for <code>dev_tt.match_question.match_id</code>.
     */
    public void setMatchId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dev_tt.match_question.match_id</code>.
     */
    public Integer getMatchId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dev_tt.match_question.num</code>.
     */
    public void setNum(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>dev_tt.match_question.num</code>.
     */
    public Integer getNum() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>dev_tt.match_question.unit_id</code>.
     */
    public void setUnitId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>dev_tt.match_question.unit_id</code>.
     */
    public String getUnitId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>dev_tt.match_question.question_mode</code>.
     */
    public void setQuestionMode(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>dev_tt.match_question.question_mode</code>.
     */
    public Integer getQuestionMode() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>dev_tt.match_question.alt_ids</code>.
     */
    public void setAltIds(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>dev_tt.match_question.alt_ids</code>.
     */
    public String getAltIds() {
        return (String) get(4);
    }

    /**
     * Setter for <code>dev_tt.match_question.usera_result</code>.
     */
    public void setUseraResult(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>dev_tt.match_question.usera_result</code>.
     */
    public String getUseraResult() {
        return (String) get(5);
    }

    /**
     * Setter for <code>dev_tt.match_question.userb_result</code>.
     */
    public void setUserbResult(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>dev_tt.match_question.userb_result</code>.
     */
    public String getUserbResult() {
        return (String) get(6);
    }

    /**
     * Setter for <code>dev_tt.match_question.last_mod</code>.
     */
    public void setLastMod(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>dev_tt.match_question.last_mod</code>.
     */
    public Timestamp getLastMod() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, String, Integer, String, String, String, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, String, Integer, String, String, String, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MatchQuestion.MATCH_QUESTION.MATCH_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return MatchQuestion.MATCH_QUESTION.NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MatchQuestion.MATCH_QUESTION.UNIT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return MatchQuestion.MATCH_QUESTION.QUESTION_MODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return MatchQuestion.MATCH_QUESTION.ALT_IDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return MatchQuestion.MATCH_QUESTION.USERA_RESULT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return MatchQuestion.MATCH_QUESTION.USERB_RESULT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return MatchQuestion.MATCH_QUESTION.LAST_MOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getMatchId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getUnitId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getQuestionMode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getAltIds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getUseraResult();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getUserbResult();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getMatchId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUnitId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getQuestionMode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAltIds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUseraResult();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getUserbResult();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchQuestionRecord value1(Integer value) {
        setMatchId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchQuestionRecord value2(Integer value) {
        setNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchQuestionRecord value3(String value) {
        setUnitId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchQuestionRecord value4(Integer value) {
        setQuestionMode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchQuestionRecord value5(String value) {
        setAltIds(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchQuestionRecord value6(String value) {
        setUseraResult(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchQuestionRecord value7(String value) {
        setUserbResult(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchQuestionRecord value8(Timestamp value) {
        setLastMod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchQuestionRecord values(Integer value1, Integer value2, String value3, Integer value4, String value5, String value6, String value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MatchQuestionRecord
     */
    public MatchQuestionRecord() {
        super(MatchQuestion.MATCH_QUESTION);
    }

    /**
     * Create a detached, initialised MatchQuestionRecord
     */
    public MatchQuestionRecord(Integer matchId, Integer num, String unitId, Integer questionMode, String altIds, String useraResult, String userbResult, Timestamp lastMod) {
        super(MatchQuestion.MATCH_QUESTION);

        set(0, matchId);
        set(1, num);
        set(2, unitId);
        set(3, questionMode);
        set(4, altIds);
        set(5, useraResult);
        set(6, userbResult);
        set(7, lastMod);
    }
}
