/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.dev_tt.tables.PhraseInfo;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PhraseInfoRecord extends TableRecordImpl<PhraseInfoRecord> implements Record5<Integer, Integer, String, Integer, Timestamp> {

    private static final long serialVersionUID = 1575095536;

    /**
     * Setter for <code>dev_tt.phrase_info.phrase_id</code>.
     */
    public void setPhraseId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dev_tt.phrase_info.phrase_id</code>.
     */
    public Integer getPhraseId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dev_tt.phrase_info.scene_id</code>.
     */
    public void setSceneId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>dev_tt.phrase_info.scene_id</code>.
     */
    public Integer getSceneId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>dev_tt.phrase_info.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>dev_tt.phrase_info.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>dev_tt.phrase_info.generation</code>.
     */
    public void setGeneration(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>dev_tt.phrase_info.generation</code>.
     */
    public Integer getGeneration() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>dev_tt.phrase_info.last_mod</code>.
     */
    public void setLastMod(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>dev_tt.phrase_info.last_mod</code>.
     */
    public Timestamp getLastMod() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, Integer, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, Integer, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return PhraseInfo.PHRASE_INFO.PHRASE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return PhraseInfo.PHRASE_INFO.SCENE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PhraseInfo.PHRASE_INFO.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return PhraseInfo.PHRASE_INFO.GENERATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return PhraseInfo.PHRASE_INFO.LAST_MOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getPhraseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getSceneId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getGeneration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPhraseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSceneId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getGeneration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhraseInfoRecord value1(Integer value) {
        setPhraseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhraseInfoRecord value2(Integer value) {
        setSceneId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhraseInfoRecord value3(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhraseInfoRecord value4(Integer value) {
        setGeneration(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhraseInfoRecord value5(Timestamp value) {
        setLastMod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhraseInfoRecord values(Integer value1, Integer value2, String value3, Integer value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PhraseInfoRecord
     */
    public PhraseInfoRecord() {
        super(PhraseInfo.PHRASE_INFO);
    }

    /**
     * Create a detached, initialised PhraseInfoRecord
     */
    public PhraseInfoRecord(Integer phraseId, Integer sceneId, String type, Integer generation, Timestamp lastMod) {
        super(PhraseInfo.PHRASE_INFO);

        set(0, phraseId);
        set(1, sceneId);
        set(2, type);
        set(3, generation);
        set(4, lastMod);
    }
}
