/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.dev_tt.tables.Phrase;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PhraseRecord extends UpdatableRecordImpl<PhraseRecord> implements Record13<Integer, Integer, Byte, String, String, Byte, String, String, String, String, String, String, Timestamp> {

    private static final long serialVersionUID = 18941063;

    /**
     * Setter for <code>dev_tt.phrase.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dev_tt.phrase.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dev_tt.phrase.en_id</code>.
     */
    public void setEnId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>dev_tt.phrase.en_id</code>.
     */
    public Integer getEnId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>dev_tt.phrase.lang_id</code>.
     */
    public void setLangId(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>dev_tt.phrase.lang_id</code>.
     */
    public Byte getLangId() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>dev_tt.phrase.display</code>.
     */
    public void setDisplay(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>dev_tt.phrase.display</code>.
     */
    public String getDisplay() {
        return (String) get(3);
    }

    /**
     * Setter for <code>dev_tt.phrase.pronounce</code>.
     */
    public void setPronounce(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>dev_tt.phrase.pronounce</code>.
     */
    public String getPronounce() {
        return (String) get(4);
    }

    /**
     * Setter for <code>dev_tt.phrase.token_count</code>.
     */
    public void setTokenCount(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>dev_tt.phrase.token_count</code>.
     */
    public Byte getTokenCount() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>dev_tt.phrase.token_ids</code>.
     */
    public void setTokenIds(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>dev_tt.phrase.token_ids</code>.
     */
    public String getTokenIds() {
        return (String) get(6);
    }

    /**
     * Setter for <code>dev_tt.phrase.sub_ids</code>.
     */
    public void setSubIds(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>dev_tt.phrase.sub_ids</code>.
     */
    public String getSubIds() {
        return (String) get(7);
    }

    /**
     * Setter for <code>dev_tt.phrase.audio</code>.
     */
    public void setAudio(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>dev_tt.phrase.audio</code>.
     */
    public String getAudio() {
        return (String) get(8);
    }

    /**
     * Setter for <code>dev_tt.phrase.audio_id</code>.
     */
    public void setAudioId(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>dev_tt.phrase.audio_id</code>.
     */
    public String getAudioId() {
        return (String) get(9);
    }

    /**
     * Setter for <code>dev_tt.phrase.active</code>.
     */
    public void setActive(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>dev_tt.phrase.active</code>.
     */
    public String getActive() {
        return (String) get(10);
    }

    /**
     * Setter for <code>dev_tt.phrase.reviewed</code>.
     */
    public void setReviewed(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>dev_tt.phrase.reviewed</code>.
     */
    public String getReviewed() {
        return (String) get(11);
    }

    /**
     * Setter for <code>dev_tt.phrase.last_mod</code>.
     */
    public void setLastMod(Timestamp value) {
        set(12, value);
    }

    /**
     * Getter for <code>dev_tt.phrase.last_mod</code>.
     */
    public Timestamp getLastMod() {
        return (Timestamp) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Integer, Byte, String, String, Byte, String, String, String, String, String, String, Timestamp> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Integer, Byte, String, String, Byte, String, String, String, String, String, String, Timestamp> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Phrase.PHRASE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Phrase.PHRASE.EN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return Phrase.PHRASE.LANG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Phrase.PHRASE.DISPLAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Phrase.PHRASE.PRONOUNCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return Phrase.PHRASE.TOKEN_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Phrase.PHRASE.TOKEN_IDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Phrase.PHRASE.SUB_IDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Phrase.PHRASE.AUDIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Phrase.PHRASE.AUDIO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Phrase.PHRASE.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Phrase.PHRASE.REVIEWED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return Phrase.PHRASE.LAST_MOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getEnId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component3() {
        return getLangId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDisplay();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getPronounce();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component6() {
        return getTokenCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getTokenIds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getSubIds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getAudio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getAudioId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getReviewed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component13() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getEnId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getLangId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDisplay();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPronounce();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getTokenCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getTokenIds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getSubIds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getAudio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getAudioId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getReviewed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhraseRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhraseRecord value2(Integer value) {
        setEnId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhraseRecord value3(Byte value) {
        setLangId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhraseRecord value4(String value) {
        setDisplay(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhraseRecord value5(String value) {
        setPronounce(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhraseRecord value6(Byte value) {
        setTokenCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhraseRecord value7(String value) {
        setTokenIds(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhraseRecord value8(String value) {
        setSubIds(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhraseRecord value9(String value) {
        setAudio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhraseRecord value10(String value) {
        setAudioId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhraseRecord value11(String value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhraseRecord value12(String value) {
        setReviewed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhraseRecord value13(Timestamp value) {
        setLastMod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhraseRecord values(Integer value1, Integer value2, Byte value3, String value4, String value5, Byte value6, String value7, String value8, String value9, String value10, String value11, String value12, Timestamp value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PhraseRecord
     */
    public PhraseRecord() {
        super(Phrase.PHRASE);
    }

    /**
     * Create a detached, initialised PhraseRecord
     */
    public PhraseRecord(Integer id, Integer enId, Byte langId, String display, String pronounce, Byte tokenCount, String tokenIds, String subIds, String audio, String audioId, String active, String reviewed, Timestamp lastMod) {
        super(Phrase.PHRASE);

        set(0, id);
        set(1, enId);
        set(2, langId);
        set(3, display);
        set(4, pronounce);
        set(5, tokenCount);
        set(6, tokenIds);
        set(7, subIds);
        set(8, audio);
        set(9, audioId);
        set(10, active);
        set(11, reviewed);
        set(12, lastMod);
    }
}
