/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.dev_tt.tables.Scene;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SceneRecord extends UpdatableRecordImpl<SceneRecord> implements Record8<Integer, Integer, Integer, String, String, Integer, String, Timestamp> {

    private static final long serialVersionUID = 132535908;

    /**
     * Setter for <code>dev_tt.scene.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dev_tt.scene.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dev_tt.scene.town_id</code>.
     */
    public void setTownId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>dev_tt.scene.town_id</code>.
     */
    public Integer getTownId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>dev_tt.scene.phrase_id</code>.
     */
    public void setPhraseId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>dev_tt.scene.phrase_id</code>.
     */
    public Integer getPhraseId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>dev_tt.scene.desc</code>.
     */
    public void setDesc(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>dev_tt.scene.desc</code>.
     */
    public String getDesc() {
        return (String) get(3);
    }

    /**
     * Setter for <code>dev_tt.scene.filename</code>.
     */
    public void setFilename(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>dev_tt.scene.filename</code>.
     */
    public String getFilename() {
        return (String) get(4);
    }

    /**
     * Setter for <code>dev_tt.scene.next_scene_id</code>.
     */
    public void setNextSceneId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>dev_tt.scene.next_scene_id</code>.
     */
    public Integer getNextSceneId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>dev_tt.scene.active</code>.
     */
    public void setActive(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>dev_tt.scene.active</code>.
     */
    public String getActive() {
        return (String) get(6);
    }

    /**
     * Setter for <code>dev_tt.scene.last_mod</code>.
     */
    public void setLastMod(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>dev_tt.scene.last_mod</code>.
     */
    public Timestamp getLastMod() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, String, String, Integer, String, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, String, String, Integer, String, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Scene.SCENE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Scene.SCENE.TOWN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Scene.SCENE.PHRASE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Scene.SCENE.DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Scene.SCENE.FILENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Scene.SCENE.NEXT_SCENE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Scene.SCENE.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Scene.SCENE.LAST_MOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getTownId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getPhraseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getFilename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getNextSceneId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getTownId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPhraseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getFilename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getNextSceneId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SceneRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SceneRecord value2(Integer value) {
        setTownId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SceneRecord value3(Integer value) {
        setPhraseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SceneRecord value4(String value) {
        setDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SceneRecord value5(String value) {
        setFilename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SceneRecord value6(Integer value) {
        setNextSceneId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SceneRecord value7(String value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SceneRecord value8(Timestamp value) {
        setLastMod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SceneRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, Integer value6, String value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SceneRecord
     */
    public SceneRecord() {
        super(Scene.SCENE);
    }

    /**
     * Create a detached, initialised SceneRecord
     */
    public SceneRecord(Integer id, Integer townId, Integer phraseId, String desc, String filename, Integer nextSceneId, String active, Timestamp lastMod) {
        super(Scene.SCENE);

        set(0, id);
        set(1, townId);
        set(2, phraseId);
        set(3, desc);
        set(4, filename);
        set(5, nextSceneId);
        set(6, active);
        set(7, lastMod);
    }
}
