/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.dev_tt.tables.SetPhrase;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SetPhraseRecord extends UpdatableRecordImpl<SetPhraseRecord> implements Record3<Integer, Integer, Timestamp> {

    private static final long serialVersionUID = -1376518622;

    /**
     * Setter for <code>dev_tt.set_phrase.set_id</code>.
     */
    public void setSetId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dev_tt.set_phrase.set_id</code>.
     */
    public Integer getSetId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dev_tt.set_phrase.phrase_id</code>.
     */
    public void setPhraseId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>dev_tt.set_phrase.phrase_id</code>.
     */
    public Integer getPhraseId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>dev_tt.set_phrase.last_mod</code>.
     */
    public void setLastMod(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>dev_tt.set_phrase.last_mod</code>.
     */
    public Timestamp getLastMod() {
        return (Timestamp) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Timestamp> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Timestamp> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SetPhrase.SET_PHRASE.SET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return SetPhrase.SET_PHRASE.PHRASE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return SetPhrase.SET_PHRASE.LAST_MOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getSetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getPhraseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getSetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPhraseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SetPhraseRecord value1(Integer value) {
        setSetId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SetPhraseRecord value2(Integer value) {
        setPhraseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SetPhraseRecord value3(Timestamp value) {
        setLastMod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SetPhraseRecord values(Integer value1, Integer value2, Timestamp value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SetPhraseRecord
     */
    public SetPhraseRecord() {
        super(SetPhrase.SET_PHRASE);
    }

    /**
     * Create a detached, initialised SetPhraseRecord
     */
    public SetPhraseRecord(Integer setId, Integer phraseId, Timestamp lastMod) {
        super(SetPhrase.SET_PHRASE);

        set(0, setId);
        set(1, phraseId);
        set(2, lastMod);
    }
}
