/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.dev_tt.tables.UserJob;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserJobRecord extends UpdatableRecordImpl<UserJobRecord> implements Record6<Integer, Integer, Integer, Integer, Integer, Timestamp> {

    private static final long serialVersionUID = -26512761;

    /**
     * Setter for <code>dev_tt.user_job.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dev_tt.user_job.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dev_tt.user_job.lang_id</code>.
     */
    public void setLangId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>dev_tt.user_job.lang_id</code>.
     */
    public Integer getLangId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>dev_tt.user_job.job_id</code>.
     */
    public void setJobId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>dev_tt.user_job.job_id</code>.
     */
    public Integer getJobId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>dev_tt.user_job.cur_count</code>.
     */
    public void setCurCount(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>dev_tt.user_job.cur_count</code>.
     */
    public Integer getCurCount() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>dev_tt.user_job.total_count</code>.
     */
    public void setTotalCount(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>dev_tt.user_job.total_count</code>.
     */
    public Integer getTotalCount() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>dev_tt.user_job.last_mod</code>.
     */
    public void setLastMod(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>dev_tt.user_job.last_mod</code>.
     */
    public Timestamp getLastMod() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<Integer, Integer, Integer> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Integer, Integer, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Integer, Integer, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserJob.USER_JOB.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserJob.USER_JOB.LANG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return UserJob.USER_JOB.JOB_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return UserJob.USER_JOB.CUR_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return UserJob.USER_JOB.TOTAL_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return UserJob.USER_JOB.LAST_MOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getLangId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getJobId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getCurCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getTotalCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLangId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getJobId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCurCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getTotalCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserJobRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserJobRecord value2(Integer value) {
        setLangId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserJobRecord value3(Integer value) {
        setJobId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserJobRecord value4(Integer value) {
        setCurCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserJobRecord value5(Integer value) {
        setTotalCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserJobRecord value6(Timestamp value) {
        setLastMod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserJobRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserJobRecord
     */
    public UserJobRecord() {
        super(UserJob.USER_JOB);
    }

    /**
     * Create a detached, initialised UserJobRecord
     */
    public UserJobRecord(Integer userId, Integer langId, Integer jobId, Integer curCount, Integer totalCount, Timestamp lastMod) {
        super(UserJob.USER_JOB);

        set(0, userId);
        set(1, langId);
        set(2, jobId);
        set(3, curCount);
        set(4, totalCount);
        set(5, lastMod);
    }
}
