/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.dev_tt.tables.UserHistory;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserHistoryRecord extends TableRecordImpl<UserHistoryRecord> implements Record5<Integer, Integer, Integer, Byte, Timestamp> {

    private static final long serialVersionUID = 564753733;

    /**
     * Setter for <code>dev_tt.user_history.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dev_tt.user_history.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dev_tt.user_history.lang_id</code>.
     */
    public void setLangId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>dev_tt.user_history.lang_id</code>.
     */
    public Integer getLangId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>dev_tt.user_history.clue_id</code>.
     */
    public void setClueId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>dev_tt.user_history.clue_id</code>.
     */
    public Integer getClueId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>dev_tt.user_history.result</code>.
     */
    public void setResult(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>dev_tt.user_history.result</code>.
     */
    public Byte getResult() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>dev_tt.user_history.last_mod</code>.
     */
    public void setLastMod(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>dev_tt.user_history.last_mod</code>.
     */
    public Timestamp getLastMod() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Byte, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Byte, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserHistory.USER_HISTORY.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserHistory.USER_HISTORY.LANG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return UserHistory.USER_HISTORY.CLUE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return UserHistory.USER_HISTORY.RESULT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return UserHistory.USER_HISTORY.LAST_MOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getLangId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getClueId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component4() {
        return getResult();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLangId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getClueId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getResult();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserHistoryRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserHistoryRecord value2(Integer value) {
        setLangId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserHistoryRecord value3(Integer value) {
        setClueId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserHistoryRecord value4(Byte value) {
        setResult(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserHistoryRecord value5(Timestamp value) {
        setLastMod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserHistoryRecord values(Integer value1, Integer value2, Integer value3, Byte value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserHistoryRecord
     */
    public UserHistoryRecord() {
        super(UserHistory.USER_HISTORY);
    }

    /**
     * Create a detached, initialised UserHistoryRecord
     */
    public UserHistoryRecord(Integer userId, Integer langId, Integer clueId, Byte result, Timestamp lastMod) {
        super(UserHistory.USER_HISTORY);

        set(0, userId);
        set(1, langId);
        set(2, clueId);
        set(3, result);
        set(4, lastMod);
    }
}
