/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.dev_tt.tables.UserTown;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserTownRecord extends UpdatableRecordImpl<UserTownRecord> implements Record5<Integer, Integer, String, String, Timestamp> {

    private static final long serialVersionUID = 1862985260;

    /**
     * Setter for <code>dev_tt.user_town.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dev_tt.user_town.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dev_tt.user_town.town_id</code>.
     */
    public void setTownId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>dev_tt.user_town.town_id</code>.
     */
    public Integer getTownId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>dev_tt.user_town.full</code>.
     */
    public void setFull(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>dev_tt.user_town.full</code>.
     */
    public String getFull() {
        return (String) get(2);
    }

    /**
     * Setter for <code>dev_tt.user_town.receipt</code>.
     */
    public void setReceipt(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>dev_tt.user_town.receipt</code>.
     */
    public String getReceipt() {
        return (String) get(3);
    }

    /**
     * Setter for <code>dev_tt.user_town.last_mod</code>.
     */
    public void setLastMod(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>dev_tt.user_town.last_mod</code>.
     */
    public Timestamp getLastMod() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, String, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, String, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserTown.USER_TOWN.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserTown.USER_TOWN.TOWN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UserTown.USER_TOWN.FULL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UserTown.USER_TOWN.RECEIPT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return UserTown.USER_TOWN.LAST_MOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getTownId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getFull();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getReceipt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getTownId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFull();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getReceipt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserTownRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserTownRecord value2(Integer value) {
        setTownId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserTownRecord value3(String value) {
        setFull(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserTownRecord value4(String value) {
        setReceipt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserTownRecord value5(Timestamp value) {
        setLastMod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserTownRecord values(Integer value1, Integer value2, String value3, String value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserTownRecord
     */
    public UserTownRecord() {
        super(UserTown.USER_TOWN);
    }

    /**
     * Create a detached, initialised UserTownRecord
     */
    public UserTownRecord(Integer userId, Integer townId, String full, String receipt, Timestamp lastMod) {
        super(UserTown.USER_TOWN);

        set(0, userId);
        set(1, townId);
        set(2, full);
        set(3, receipt);
        set(4, lastMod);
    }
}
