/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.dev_tt.tables.UserToken;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserTokenRecord extends TableRecordImpl<UserTokenRecord> implements Record7<Integer, Integer, Integer, Byte, Byte, Byte, Timestamp> {

    private static final long serialVersionUID = -1592204638;

    /**
     * Setter for <code>dev_tt.user_token.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dev_tt.user_token.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dev_tt.user_token.lang_id</code>.
     */
    public void setLangId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>dev_tt.user_token.lang_id</code>.
     */
    public Integer getLangId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>dev_tt.user_token.token_id</code>.
     */
    public void setTokenId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>dev_tt.user_token.token_id</code>.
     */
    public Integer getTokenId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>dev_tt.user_token.scorea</code>.
     */
    public void setScorea(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>dev_tt.user_token.scorea</code>.
     */
    public Byte getScorea() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>dev_tt.user_token.scoreb</code>.
     */
    public void setScoreb(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>dev_tt.user_token.scoreb</code>.
     */
    public Byte getScoreb() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>dev_tt.user_token.scorec</code>.
     */
    public void setScorec(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>dev_tt.user_token.scorec</code>.
     */
    public Byte getScorec() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>dev_tt.user_token.last_mod</code>.
     */
    public void setLastMod(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>dev_tt.user_token.last_mod</code>.
     */
    public Timestamp getLastMod() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Byte, Byte, Byte, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Byte, Byte, Byte, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserToken.USER_TOKEN.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserToken.USER_TOKEN.LANG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return UserToken.USER_TOKEN.TOKEN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return UserToken.USER_TOKEN.SCOREA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return UserToken.USER_TOKEN.SCOREB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return UserToken.USER_TOKEN.SCOREC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return UserToken.USER_TOKEN.LAST_MOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getLangId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getTokenId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component4() {
        return getScorea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component5() {
        return getScoreb();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component6() {
        return getScorec();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLangId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getTokenId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getScorea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getScoreb();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getScorec();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserTokenRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserTokenRecord value2(Integer value) {
        setLangId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserTokenRecord value3(Integer value) {
        setTokenId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserTokenRecord value4(Byte value) {
        setScorea(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserTokenRecord value5(Byte value) {
        setScoreb(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserTokenRecord value6(Byte value) {
        setScorec(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserTokenRecord value7(Timestamp value) {
        setLastMod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserTokenRecord values(Integer value1, Integer value2, Integer value3, Byte value4, Byte value5, Byte value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserTokenRecord
     */
    public UserTokenRecord() {
        super(UserToken.USER_TOKEN);
    }

    /**
     * Create a detached, initialised UserTokenRecord
     */
    public UserTokenRecord(Integer userId, Integer langId, Integer tokenId, Byte scorea, Byte scoreb, Byte scorec, Timestamp lastMod) {
        super(UserToken.USER_TOKEN);

        set(0, userId);
        set(1, langId);
        set(2, tokenId);
        set(3, scorea);
        set(4, scoreb);
        set(5, scorec);
        set(6, lastMod);
    }
}
