/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.dev_tt.tables.UserItem;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserItemRecord extends UpdatableRecordImpl<UserItemRecord> implements Record7<Integer, Integer, Integer, Integer, Integer, Integer, Timestamp> {

    private static final long serialVersionUID = 325624306;

    /**
     * Setter for <code>dev_tt.user_item.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dev_tt.user_item.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dev_tt.user_item.lang_id</code>.
     */
    public void setLangId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>dev_tt.user_item.lang_id</code>.
     */
    public Integer getLangId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>dev_tt.user_item.phrase_id</code>.
     */
    public void setPhraseId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>dev_tt.user_item.phrase_id</code>.
     */
    public Integer getPhraseId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>dev_tt.user_item.cur_count</code>.
     */
    public void setCurCount(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>dev_tt.user_item.cur_count</code>.
     */
    public Integer getCurCount() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>dev_tt.user_item.total_count</code>.
     */
    public void setTotalCount(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>dev_tt.user_item.total_count</code>.
     */
    public Integer getTotalCount() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>dev_tt.user_item.item_id</code>.
     */
    public void setItemId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>dev_tt.user_item.item_id</code>.
     */
    public Integer getItemId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>dev_tt.user_item.last_mod</code>.
     */
    public void setLastMod(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>dev_tt.user_item.last_mod</code>.
     */
    public Timestamp getLastMod() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<Integer, Integer, Integer> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Integer, Integer, Integer, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Integer, Integer, Integer, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserItem.USER_ITEM.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserItem.USER_ITEM.LANG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return UserItem.USER_ITEM.PHRASE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return UserItem.USER_ITEM.CUR_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return UserItem.USER_ITEM.TOTAL_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return UserItem.USER_ITEM.ITEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return UserItem.USER_ITEM.LAST_MOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getLangId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getPhraseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getCurCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getTotalCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLangId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPhraseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCurCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getTotalCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getLastMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserItemRecord value1(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserItemRecord value2(Integer value) {
        setLangId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserItemRecord value3(Integer value) {
        setPhraseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserItemRecord value4(Integer value) {
        setCurCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserItemRecord value5(Integer value) {
        setTotalCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserItemRecord value6(Integer value) {
        setItemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserItemRecord value7(Timestamp value) {
        setLastMod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserItemRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserItemRecord
     */
    public UserItemRecord() {
        super(UserItem.USER_ITEM);
    }

    /**
     * Create a detached, initialised UserItemRecord
     */
    public UserItemRecord(Integer userId, Integer langId, Integer phraseId, Integer curCount, Integer totalCount, Integer itemId, Timestamp lastMod) {
        super(UserItem.USER_ITEM);

        set(0, userId);
        set(1, langId);
        set(2, phraseId);
        set(3, curCount);
        set(4, totalCount);
        set(5, itemId);
        set(6, lastMod);
    }
}
