/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt;


import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.dev_tt.tables.Clue;
import org.jooq.dev_tt.tables.ClueRank;
import org.jooq.dev_tt.tables.Item;
import org.jooq.dev_tt.tables.Job;
import org.jooq.dev_tt.tables.Lang;
import org.jooq.dev_tt.tables.LangScene;
import org.jooq.dev_tt.tables.Match;
import org.jooq.dev_tt.tables.MatchAlt;
import org.jooq.dev_tt.tables.MatchQuestion;
import org.jooq.dev_tt.tables.MatchUser;
import org.jooq.dev_tt.tables.Message;
import org.jooq.dev_tt.tables.Phrase;
import org.jooq.dev_tt.tables.Scene;
import org.jooq.dev_tt.tables.Set;
import org.jooq.dev_tt.tables.SetPhrase;
import org.jooq.dev_tt.tables.Spot;
import org.jooq.dev_tt.tables.Token;
import org.jooq.dev_tt.tables.User;
import org.jooq.dev_tt.tables.UserClue;
import org.jooq.dev_tt.tables.UserItem;
import org.jooq.dev_tt.tables.UserJob;
import org.jooq.dev_tt.tables.UserLang;
import org.jooq.dev_tt.tables.UserScene;
import org.jooq.dev_tt.tables.UserSet;
import org.jooq.dev_tt.tables.UserToken;
import org.jooq.dev_tt.tables.UserTown;
import org.jooq.dev_tt.tables.records.ClueRankRecord;
import org.jooq.dev_tt.tables.records.ClueRecord;
import org.jooq.dev_tt.tables.records.ItemRecord;
import org.jooq.dev_tt.tables.records.JobRecord;
import org.jooq.dev_tt.tables.records.LangRecord;
import org.jooq.dev_tt.tables.records.LangSceneRecord;
import org.jooq.dev_tt.tables.records.MatchAltRecord;
import org.jooq.dev_tt.tables.records.MatchQuestionRecord;
import org.jooq.dev_tt.tables.records.MatchRecord;
import org.jooq.dev_tt.tables.records.MatchUserRecord;
import org.jooq.dev_tt.tables.records.MessageRecord;
import org.jooq.dev_tt.tables.records.PhraseRecord;
import org.jooq.dev_tt.tables.records.SceneRecord;
import org.jooq.dev_tt.tables.records.SetPhraseRecord;
import org.jooq.dev_tt.tables.records.SetRecord;
import org.jooq.dev_tt.tables.records.SpotRecord;
import org.jooq.dev_tt.tables.records.TokenRecord;
import org.jooq.dev_tt.tables.records.UserClueRecord;
import org.jooq.dev_tt.tables.records.UserItemRecord;
import org.jooq.dev_tt.tables.records.UserJobRecord;
import org.jooq.dev_tt.tables.records.UserLangRecord;
import org.jooq.dev_tt.tables.records.UserRecord;
import org.jooq.dev_tt.tables.records.UserSceneRecord;
import org.jooq.dev_tt.tables.records.UserSetRecord;
import org.jooq.dev_tt.tables.records.UserTokenRecord;
import org.jooq.dev_tt.tables.records.UserTownRecord;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>dev_tt</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ClueRecord, Integer> IDENTITY_CLUE = Identities0.IDENTITY_CLUE;
    public static final Identity<ItemRecord, Integer> IDENTITY_ITEM = Identities0.IDENTITY_ITEM;
    public static final Identity<JobRecord, Integer> IDENTITY_JOB = Identities0.IDENTITY_JOB;
    public static final Identity<LangRecord, Integer> IDENTITY_LANG = Identities0.IDENTITY_LANG;
    public static final Identity<MatchRecord, Integer> IDENTITY_MATCH = Identities0.IDENTITY_MATCH;
    public static final Identity<MessageRecord, Integer> IDENTITY_MESSAGE = Identities0.IDENTITY_MESSAGE;
    public static final Identity<PhraseRecord, Integer> IDENTITY_PHRASE = Identities0.IDENTITY_PHRASE;
    public static final Identity<SceneRecord, Integer> IDENTITY_SCENE = Identities0.IDENTITY_SCENE;
    public static final Identity<SpotRecord, Integer> IDENTITY_SPOT = Identities0.IDENTITY_SPOT;
    public static final Identity<TokenRecord, Integer> IDENTITY_TOKEN = Identities0.IDENTITY_TOKEN;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ClueRecord> KEY_CLUE_PRIMARY = UniqueKeys0.KEY_CLUE_PRIMARY;
    public static final UniqueKey<ClueRankRecord> KEY_CLUE_RANK_CLUE_ID = UniqueKeys0.KEY_CLUE_RANK_CLUE_ID;
    public static final UniqueKey<ItemRecord> KEY_ITEM_PRIMARY = UniqueKeys0.KEY_ITEM_PRIMARY;
    public static final UniqueKey<JobRecord> KEY_JOB_PRIMARY = UniqueKeys0.KEY_JOB_PRIMARY;
    public static final UniqueKey<LangRecord> KEY_LANG_PRIMARY = UniqueKeys0.KEY_LANG_PRIMARY;
    public static final UniqueKey<LangSceneRecord> KEY_LANG_SCENE_LANG_ID = UniqueKeys0.KEY_LANG_SCENE_LANG_ID;
    public static final UniqueKey<MatchRecord> KEY_MATCH_PRIMARY = UniqueKeys0.KEY_MATCH_PRIMARY;
    public static final UniqueKey<MatchAltRecord> KEY_MATCH_ALT_PRIMARY = UniqueKeys0.KEY_MATCH_ALT_PRIMARY;
    public static final UniqueKey<MatchQuestionRecord> KEY_MATCH_QUESTION_MATCH_CLUE_IDX = UniqueKeys0.KEY_MATCH_QUESTION_MATCH_CLUE_IDX;
    public static final UniqueKey<MatchUserRecord> KEY_MATCH_USER_PRIMARY = UniqueKeys0.KEY_MATCH_USER_PRIMARY;
    public static final UniqueKey<MessageRecord> KEY_MESSAGE_PRIMARY = UniqueKeys0.KEY_MESSAGE_PRIMARY;
    public static final UniqueKey<PhraseRecord> KEY_PHRASE_PRIMARY = UniqueKeys0.KEY_PHRASE_PRIMARY;
    public static final UniqueKey<SceneRecord> KEY_SCENE_PRIMARY = UniqueKeys0.KEY_SCENE_PRIMARY;
    public static final UniqueKey<SetRecord> KEY_SET_PRIMARY = UniqueKeys0.KEY_SET_PRIMARY;
    public static final UniqueKey<SetPhraseRecord> KEY_SET_PHRASE_PRIMARY = UniqueKeys0.KEY_SET_PHRASE_PRIMARY;
    public static final UniqueKey<SpotRecord> KEY_SPOT_SCENE_ID = UniqueKeys0.KEY_SPOT_SCENE_ID;
    public static final UniqueKey<TokenRecord> KEY_TOKEN_PRIMARY = UniqueKeys0.KEY_TOKEN_PRIMARY;
    public static final UniqueKey<TokenRecord> KEY_TOKEN_LANG_ID = UniqueKeys0.KEY_TOKEN_LANG_ID;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;
    public static final UniqueKey<UserClueRecord> KEY_USER_CLUE_PRIMARY = UniqueKeys0.KEY_USER_CLUE_PRIMARY;
    public static final UniqueKey<UserItemRecord> KEY_USER_ITEM_PRIMARY = UniqueKeys0.KEY_USER_ITEM_PRIMARY;
    public static final UniqueKey<UserJobRecord> KEY_USER_JOB_PRIMARY = UniqueKeys0.KEY_USER_JOB_PRIMARY;
    public static final UniqueKey<UserLangRecord> KEY_USER_LANG_PRIMARY = UniqueKeys0.KEY_USER_LANG_PRIMARY;
    public static final UniqueKey<UserSceneRecord> KEY_USER_SCENE_USER_ID = UniqueKeys0.KEY_USER_SCENE_USER_ID;
    public static final UniqueKey<UserSetRecord> KEY_USER_SET_PRIMARY = UniqueKeys0.KEY_USER_SET_PRIMARY;
    public static final UniqueKey<UserTokenRecord> KEY_USER_TOKEN_USER_ID = UniqueKeys0.KEY_USER_TOKEN_USER_ID;
    public static final UniqueKey<UserTownRecord> KEY_USER_TOWN_PRIMARY = UniqueKeys0.KEY_USER_TOWN_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<ClueRecord, Integer> IDENTITY_CLUE = createIdentity(Clue.CLUE, Clue.CLUE.ID);
        public static Identity<ItemRecord, Integer> IDENTITY_ITEM = createIdentity(Item.ITEM, Item.ITEM.ID);
        public static Identity<JobRecord, Integer> IDENTITY_JOB = createIdentity(Job.JOB, Job.JOB.ID);
        public static Identity<LangRecord, Integer> IDENTITY_LANG = createIdentity(Lang.LANG, Lang.LANG.ID);
        public static Identity<MatchRecord, Integer> IDENTITY_MATCH = createIdentity(Match.MATCH, Match.MATCH.ID);
        public static Identity<MessageRecord, Integer> IDENTITY_MESSAGE = createIdentity(Message.MESSAGE, Message.MESSAGE.ID);
        public static Identity<PhraseRecord, Integer> IDENTITY_PHRASE = createIdentity(Phrase.PHRASE, Phrase.PHRASE.ID);
        public static Identity<SceneRecord, Integer> IDENTITY_SCENE = createIdentity(Scene.SCENE, Scene.SCENE.ID);
        public static Identity<SpotRecord, Integer> IDENTITY_SPOT = createIdentity(Spot.SPOT, Spot.SPOT.ID);
        public static Identity<TokenRecord, Integer> IDENTITY_TOKEN = createIdentity(Token.TOKEN, Token.TOKEN.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ClueRecord> KEY_CLUE_PRIMARY = createUniqueKey(Clue.CLUE, "KEY_clue_PRIMARY", Clue.CLUE.ID);
        public static final UniqueKey<ClueRankRecord> KEY_CLUE_RANK_CLUE_ID = createUniqueKey(ClueRank.CLUE_RANK, "KEY_clue_rank_clue_id", ClueRank.CLUE_RANK.CLUE_ID, ClueRank.CLUE_RANK.LANG_ID, ClueRank.CLUE_RANK.SCENE_ID);
        public static final UniqueKey<ItemRecord> KEY_ITEM_PRIMARY = createUniqueKey(Item.ITEM, "KEY_item_PRIMARY", Item.ITEM.ID);
        public static final UniqueKey<JobRecord> KEY_JOB_PRIMARY = createUniqueKey(Job.JOB, "KEY_job_PRIMARY", Job.JOB.ID);
        public static final UniqueKey<LangRecord> KEY_LANG_PRIMARY = createUniqueKey(Lang.LANG, "KEY_lang_PRIMARY", Lang.LANG.ID);
        public static final UniqueKey<LangSceneRecord> KEY_LANG_SCENE_LANG_ID = createUniqueKey(LangScene.LANG_SCENE, "KEY_lang_scene_lang_id", LangScene.LANG_SCENE.LANG_ID, LangScene.LANG_SCENE.SCENE_ID);
        public static final UniqueKey<MatchRecord> KEY_MATCH_PRIMARY = createUniqueKey(Match.MATCH, "KEY_match_PRIMARY", Match.MATCH.ID);
        public static final UniqueKey<MatchAltRecord> KEY_MATCH_ALT_PRIMARY = createUniqueKey(MatchAlt.MATCH_ALT, "KEY_match_alt_PRIMARY", MatchAlt.MATCH_ALT.ALT_ID, MatchAlt.MATCH_ALT.UNIT_ID);
        public static final UniqueKey<MatchQuestionRecord> KEY_MATCH_QUESTION_MATCH_CLUE_IDX = createUniqueKey(MatchQuestion.MATCH_QUESTION, "KEY_match_question_match_clue_idx", MatchQuestion.MATCH_QUESTION.UNIT_ID, MatchQuestion.MATCH_QUESTION.MATCH_ID);
        public static final UniqueKey<MatchUserRecord> KEY_MATCH_USER_PRIMARY = createUniqueKey(MatchUser.MATCH_USER, "KEY_match_user_PRIMARY", MatchUser.MATCH_USER.MATCH_ID, MatchUser.MATCH_USER.USER_ID);
        public static final UniqueKey<MessageRecord> KEY_MESSAGE_PRIMARY = createUniqueKey(Message.MESSAGE, "KEY_message_PRIMARY", Message.MESSAGE.ID);
        public static final UniqueKey<PhraseRecord> KEY_PHRASE_PRIMARY = createUniqueKey(Phrase.PHRASE, "KEY_phrase_PRIMARY", Phrase.PHRASE.ID);
        public static final UniqueKey<SceneRecord> KEY_SCENE_PRIMARY = createUniqueKey(Scene.SCENE, "KEY_scene_PRIMARY", Scene.SCENE.ID);
        public static final UniqueKey<SetRecord> KEY_SET_PRIMARY = createUniqueKey(Set.SET, "KEY_set_PRIMARY", Set.SET.ID);
        public static final UniqueKey<SetPhraseRecord> KEY_SET_PHRASE_PRIMARY = createUniqueKey(SetPhrase.SET_PHRASE, "KEY_set_phrase_PRIMARY", SetPhrase.SET_PHRASE.SET_ID, SetPhrase.SET_PHRASE.PHRASE_ID);
        public static final UniqueKey<SpotRecord> KEY_SPOT_SCENE_ID = createUniqueKey(Spot.SPOT, "KEY_spot_scene_id", Spot.SPOT.ID, Spot.SPOT.SCENE_ID);
        public static final UniqueKey<TokenRecord> KEY_TOKEN_PRIMARY = createUniqueKey(Token.TOKEN, "KEY_token_PRIMARY", Token.TOKEN.ID);
        public static final UniqueKey<TokenRecord> KEY_TOKEN_LANG_ID = createUniqueKey(Token.TOKEN, "KEY_token_lang_id", Token.TOKEN.LANG_ID, Token.TOKEN.DISPLAY);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = createUniqueKey(User.USER, "KEY_user_PRIMARY", User.USER.ID);
        public static final UniqueKey<UserClueRecord> KEY_USER_CLUE_PRIMARY = createUniqueKey(UserClue.USER_CLUE, "KEY_user_clue_PRIMARY", UserClue.USER_CLUE.USER_ID, UserClue.USER_CLUE.CLUE_ID, UserClue.USER_CLUE.LANG_ID);
        public static final UniqueKey<UserItemRecord> KEY_USER_ITEM_PRIMARY = createUniqueKey(UserItem.USER_ITEM, "KEY_user_item_PRIMARY", UserItem.USER_ITEM.USER_ID, UserItem.USER_ITEM.LANG_ID, UserItem.USER_ITEM.PHRASE_ID);
        public static final UniqueKey<UserJobRecord> KEY_USER_JOB_PRIMARY = createUniqueKey(UserJob.USER_JOB, "KEY_user_job_PRIMARY", UserJob.USER_JOB.USER_ID, UserJob.USER_JOB.LANG_ID, UserJob.USER_JOB.JOB_ID);
        public static final UniqueKey<UserLangRecord> KEY_USER_LANG_PRIMARY = createUniqueKey(UserLang.USER_LANG, "KEY_user_lang_PRIMARY", UserLang.USER_LANG.USER_ID, UserLang.USER_LANG.LANG_ID);
        public static final UniqueKey<UserSceneRecord> KEY_USER_SCENE_USER_ID = createUniqueKey(UserScene.USER_SCENE, "KEY_user_scene_user_id", UserScene.USER_SCENE.USER_ID, UserScene.USER_SCENE.LANG_ID, UserScene.USER_SCENE.SCENE_ID);
        public static final UniqueKey<UserSetRecord> KEY_USER_SET_PRIMARY = createUniqueKey(UserSet.USER_SET, "KEY_user_set_PRIMARY", UserSet.USER_SET.SET_ID, UserSet.USER_SET.LANG_ID, UserSet.USER_SET.USER_ID);
        public static final UniqueKey<UserTokenRecord> KEY_USER_TOKEN_USER_ID = createUniqueKey(UserToken.USER_TOKEN, "KEY_user_token_user_id", UserToken.USER_TOKEN.USER_ID, UserToken.USER_TOKEN.LANG_ID, UserToken.USER_TOKEN.TOKEN_ID);
        public static final UniqueKey<UserTownRecord> KEY_USER_TOWN_PRIMARY = createUniqueKey(UserTown.USER_TOWN, "KEY_user_town_PRIMARY", UserTown.USER_TOWN.USER_ID, UserTown.USER_TOWN.TOWN_ID);
    }
}
