/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt;


import javax.annotation.Generated;

import org.jooq.dev_tt.tables.Clue;
import org.jooq.dev_tt.tables.ClueRank;
import org.jooq.dev_tt.tables.Item;
import org.jooq.dev_tt.tables.Job;
import org.jooq.dev_tt.tables.Lang;
import org.jooq.dev_tt.tables.LangScene;
import org.jooq.dev_tt.tables.Match;
import org.jooq.dev_tt.tables.MatchAlt;
import org.jooq.dev_tt.tables.MatchQuestion;
import org.jooq.dev_tt.tables.MatchUser;
import org.jooq.dev_tt.tables.Message;
import org.jooq.dev_tt.tables.Phrase;
import org.jooq.dev_tt.tables.PhraseInfo;
import org.jooq.dev_tt.tables.Scene;
import org.jooq.dev_tt.tables.Set;
import org.jooq.dev_tt.tables.SetPhrase;
import org.jooq.dev_tt.tables.Spot;
import org.jooq.dev_tt.tables.Token;
import org.jooq.dev_tt.tables.User;
import org.jooq.dev_tt.tables.UserClue;
import org.jooq.dev_tt.tables.UserHistory;
import org.jooq.dev_tt.tables.UserItem;
import org.jooq.dev_tt.tables.UserJob;
import org.jooq.dev_tt.tables.UserLang;
import org.jooq.dev_tt.tables.UserScene;
import org.jooq.dev_tt.tables.UserSet;
import org.jooq.dev_tt.tables.UserToken;
import org.jooq.dev_tt.tables.UserTown;


/**
 * Convenience access to all tables in dev_tt
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>dev_tt.clue</code>.
     */
    public static final Clue CLUE = org.jooq.dev_tt.tables.Clue.CLUE;

    /**
     * The table <code>dev_tt.clue_rank</code>.
     */
    public static final ClueRank CLUE_RANK = org.jooq.dev_tt.tables.ClueRank.CLUE_RANK;

    /**
     * The table <code>dev_tt.item</code>.
     */
    public static final Item ITEM = org.jooq.dev_tt.tables.Item.ITEM;

    /**
     * The table <code>dev_tt.job</code>.
     */
    public static final Job JOB = org.jooq.dev_tt.tables.Job.JOB;

    /**
     * The table <code>dev_tt.lang</code>.
     */
    public static final Lang LANG = org.jooq.dev_tt.tables.Lang.LANG;

    /**
     * The table <code>dev_tt.lang_scene</code>.
     */
    public static final LangScene LANG_SCENE = org.jooq.dev_tt.tables.LangScene.LANG_SCENE;

    /**
     * The table <code>dev_tt.match</code>.
     */
    public static final Match MATCH = org.jooq.dev_tt.tables.Match.MATCH;

    /**
     * The table <code>dev_tt.match_alt</code>.
     */
    public static final MatchAlt MATCH_ALT = org.jooq.dev_tt.tables.MatchAlt.MATCH_ALT;

    /**
     * The table <code>dev_tt.match_question</code>.
     */
    public static final MatchQuestion MATCH_QUESTION = org.jooq.dev_tt.tables.MatchQuestion.MATCH_QUESTION;

    /**
     * The table <code>dev_tt.match_user</code>.
     */
    public static final MatchUser MATCH_USER = org.jooq.dev_tt.tables.MatchUser.MATCH_USER;

    /**
     * The table <code>dev_tt.message</code>.
     */
    public static final Message MESSAGE = org.jooq.dev_tt.tables.Message.MESSAGE;

    /**
     * The table <code>dev_tt.phrase</code>.
     */
    public static final Phrase PHRASE = org.jooq.dev_tt.tables.Phrase.PHRASE;

    /**
     * The table <code>dev_tt.phrase_info</code>.
     */
    public static final PhraseInfo PHRASE_INFO = org.jooq.dev_tt.tables.PhraseInfo.PHRASE_INFO;

    /**
     * The table <code>dev_tt.scene</code>.
     */
    public static final Scene SCENE = org.jooq.dev_tt.tables.Scene.SCENE;

    /**
     * The table <code>dev_tt.set</code>.
     */
    public static final Set SET = org.jooq.dev_tt.tables.Set.SET;

    /**
     * The table <code>dev_tt.set_phrase</code>.
     */
    public static final SetPhrase SET_PHRASE = org.jooq.dev_tt.tables.SetPhrase.SET_PHRASE;

    /**
     * The table <code>dev_tt.spot</code>.
     */
    public static final Spot SPOT = org.jooq.dev_tt.tables.Spot.SPOT;

    /**
     * The table <code>dev_tt.token</code>.
     */
    public static final Token TOKEN = org.jooq.dev_tt.tables.Token.TOKEN;

    /**
     * The table <code>dev_tt.user</code>.
     */
    public static final User USER = org.jooq.dev_tt.tables.User.USER;

    /**
     * The table <code>dev_tt.user_clue</code>.
     */
    public static final UserClue USER_CLUE = org.jooq.dev_tt.tables.UserClue.USER_CLUE;

    /**
     * The table <code>dev_tt.user_history</code>.
     */
    public static final UserHistory USER_HISTORY = org.jooq.dev_tt.tables.UserHistory.USER_HISTORY;

    /**
     * The table <code>dev_tt.user_item</code>.
     */
    public static final UserItem USER_ITEM = org.jooq.dev_tt.tables.UserItem.USER_ITEM;

    /**
     * The table <code>dev_tt.user_job</code>.
     */
    public static final UserJob USER_JOB = org.jooq.dev_tt.tables.UserJob.USER_JOB;

    /**
     * The table <code>dev_tt.user_lang</code>.
     */
    public static final UserLang USER_LANG = org.jooq.dev_tt.tables.UserLang.USER_LANG;

    /**
     * The table <code>dev_tt.user_scene</code>.
     */
    public static final UserScene USER_SCENE = org.jooq.dev_tt.tables.UserScene.USER_SCENE;

    /**
     * The table <code>dev_tt.user_set</code>.
     */
    public static final UserSet USER_SET = org.jooq.dev_tt.tables.UserSet.USER_SET;

    /**
     * The table <code>dev_tt.user_token</code>.
     */
    public static final UserToken USER_TOKEN = org.jooq.dev_tt.tables.UserToken.USER_TOKEN;

    /**
     * The table <code>dev_tt.user_town</code>.
     */
    public static final UserTown USER_TOWN = org.jooq.dev_tt.tables.UserTown.USER_TOWN;
}
