/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LangScene implements Serializable {

    private static final long serialVersionUID = 1387387831;

    private Integer   langId;
    private Integer   sceneId;
    private Integer   maxTokens;
    private Integer   rankedClues;
    private Timestamp lastMod;

    public LangScene() {}

    public LangScene(LangScene value) {
        this.langId = value.langId;
        this.sceneId = value.sceneId;
        this.maxTokens = value.maxTokens;
        this.rankedClues = value.rankedClues;
        this.lastMod = value.lastMod;
    }

    public LangScene(
        Integer   langId,
        Integer   sceneId,
        Integer   maxTokens,
        Integer   rankedClues,
        Timestamp lastMod
    ) {
        this.langId = langId;
        this.sceneId = sceneId;
        this.maxTokens = maxTokens;
        this.rankedClues = rankedClues;
        this.lastMod = lastMod;
    }

    public Integer getLangId() {
        return this.langId;
    }

    public void setLangId(Integer langId) {
        this.langId = langId;
    }

    public Integer getSceneId() {
        return this.sceneId;
    }

    public void setSceneId(Integer sceneId) {
        this.sceneId = sceneId;
    }

    public Integer getMaxTokens() {
        return this.maxTokens;
    }

    public void setMaxTokens(Integer maxTokens) {
        this.maxTokens = maxTokens;
    }

    public Integer getRankedClues() {
        return this.rankedClues;
    }

    public void setRankedClues(Integer rankedClues) {
        this.rankedClues = rankedClues;
    }

    public Timestamp getLastMod() {
        return this.lastMod;
    }

    public void setLastMod(Timestamp lastMod) {
        this.lastMod = lastMod;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LangScene (");

        sb.append(langId);
        sb.append(", ").append(sceneId);
        sb.append(", ").append(maxTokens);
        sb.append(", ").append(rankedClues);
        sb.append(", ").append(lastMod);

        sb.append(")");
        return sb.toString();
    }
}
