/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Lang implements Serializable {

    private static final long serialVersionUID = -77840029;

    private Integer   id;
    private String    code;
    private String    desc;
    private Integer   tokenizeType;
    private Timestamp lastMod;
    private Integer   modBy;

    public Lang() {}

    public Lang(Lang value) {
        this.id = value.id;
        this.code = value.code;
        this.desc = value.desc;
        this.tokenizeType = value.tokenizeType;
        this.lastMod = value.lastMod;
        this.modBy = value.modBy;
    }

    public Lang(
        Integer   id,
        String    code,
        String    desc,
        Integer   tokenizeType,
        Timestamp lastMod,
        Integer   modBy
    ) {
        this.id = id;
        this.code = code;
        this.desc = desc;
        this.tokenizeType = tokenizeType;
        this.lastMod = lastMod;
        this.modBy = modBy;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getDesc() {
        return this.desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public Integer getTokenizeType() {
        return this.tokenizeType;
    }

    public void setTokenizeType(Integer tokenizeType) {
        this.tokenizeType = tokenizeType;
    }

    public Timestamp getLastMod() {
        return this.lastMod;
    }

    public void setLastMod(Timestamp lastMod) {
        this.lastMod = lastMod;
    }

    public Integer getModBy() {
        return this.modBy;
    }

    public void setModBy(Integer modBy) {
        this.modBy = modBy;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Lang (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(desc);
        sb.append(", ").append(tokenizeType);
        sb.append(", ").append(lastMod);
        sb.append(", ").append(modBy);

        sb.append(")");
        return sb.toString();
    }
}
