/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MatchUser implements Serializable {

    private static final long serialVersionUID = 1830531970;

    private Integer   matchId;
    private Integer   userId;
    private Integer   oppId;
    private Byte      state;
    private Integer   xp;
    private String    results;
    private Integer   correctCount;
    private Integer   xpEarned;
    private Integer   coinsEarned;
    private Timestamp created;

    public MatchUser() {}

    public MatchUser(MatchUser value) {
        this.matchId = value.matchId;
        this.userId = value.userId;
        this.oppId = value.oppId;
        this.state = value.state;
        this.xp = value.xp;
        this.results = value.results;
        this.correctCount = value.correctCount;
        this.xpEarned = value.xpEarned;
        this.coinsEarned = value.coinsEarned;
        this.created = value.created;
    }

    public MatchUser(
        Integer   matchId,
        Integer   userId,
        Integer   oppId,
        Byte      state,
        Integer   xp,
        String    results,
        Integer   correctCount,
        Integer   xpEarned,
        Integer   coinsEarned,
        Timestamp created
    ) {
        this.matchId = matchId;
        this.userId = userId;
        this.oppId = oppId;
        this.state = state;
        this.xp = xp;
        this.results = results;
        this.correctCount = correctCount;
        this.xpEarned = xpEarned;
        this.coinsEarned = coinsEarned;
        this.created = created;
    }

    public Integer getMatchId() {
        return this.matchId;
    }

    public void setMatchId(Integer matchId) {
        this.matchId = matchId;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getOppId() {
        return this.oppId;
    }

    public void setOppId(Integer oppId) {
        this.oppId = oppId;
    }

    public Byte getState() {
        return this.state;
    }

    public void setState(Byte state) {
        this.state = state;
    }

    public Integer getXp() {
        return this.xp;
    }

    public void setXp(Integer xp) {
        this.xp = xp;
    }

    public String getResults() {
        return this.results;
    }

    public void setResults(String results) {
        this.results = results;
    }

    public Integer getCorrectCount() {
        return this.correctCount;
    }

    public void setCorrectCount(Integer correctCount) {
        this.correctCount = correctCount;
    }

    public Integer getXpEarned() {
        return this.xpEarned;
    }

    public void setXpEarned(Integer xpEarned) {
        this.xpEarned = xpEarned;
    }

    public Integer getCoinsEarned() {
        return this.coinsEarned;
    }

    public void setCoinsEarned(Integer coinsEarned) {
        this.coinsEarned = coinsEarned;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MatchUser (");

        sb.append(matchId);
        sb.append(", ").append(userId);
        sb.append(", ").append(oppId);
        sb.append(", ").append(state);
        sb.append(", ").append(xp);
        sb.append(", ").append(results);
        sb.append(", ").append(correctCount);
        sb.append(", ").append(xpEarned);
        sb.append(", ").append(coinsEarned);
        sb.append(", ").append(created);

        sb.append(")");
        return sb.toString();
    }
}
