/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MatchQuestion implements Serializable {

    private static final long serialVersionUID = 1533022140;

    private Integer   matchId;
    private Integer   num;
    private String    unitId;
    private Integer   questionMode;
    private String    altIds;
    private String    useraResult;
    private String    userbResult;
    private Timestamp lastMod;

    public MatchQuestion() {}

    public MatchQuestion(MatchQuestion value) {
        this.matchId = value.matchId;
        this.num = value.num;
        this.unitId = value.unitId;
        this.questionMode = value.questionMode;
        this.altIds = value.altIds;
        this.useraResult = value.useraResult;
        this.userbResult = value.userbResult;
        this.lastMod = value.lastMod;
    }

    public MatchQuestion(
        Integer   matchId,
        Integer   num,
        String    unitId,
        Integer   questionMode,
        String    altIds,
        String    useraResult,
        String    userbResult,
        Timestamp lastMod
    ) {
        this.matchId = matchId;
        this.num = num;
        this.unitId = unitId;
        this.questionMode = questionMode;
        this.altIds = altIds;
        this.useraResult = useraResult;
        this.userbResult = userbResult;
        this.lastMod = lastMod;
    }

    public Integer getMatchId() {
        return this.matchId;
    }

    public void setMatchId(Integer matchId) {
        this.matchId = matchId;
    }

    public Integer getNum() {
        return this.num;
    }

    public void setNum(Integer num) {
        this.num = num;
    }

    public String getUnitId() {
        return this.unitId;
    }

    public void setUnitId(String unitId) {
        this.unitId = unitId;
    }

    public Integer getQuestionMode() {
        return this.questionMode;
    }

    public void setQuestionMode(Integer questionMode) {
        this.questionMode = questionMode;
    }

    public String getAltIds() {
        return this.altIds;
    }

    public void setAltIds(String altIds) {
        this.altIds = altIds;
    }

    public String getUseraResult() {
        return this.useraResult;
    }

    public void setUseraResult(String useraResult) {
        this.useraResult = useraResult;
    }

    public String getUserbResult() {
        return this.userbResult;
    }

    public void setUserbResult(String userbResult) {
        this.userbResult = userbResult;
    }

    public Timestamp getLastMod() {
        return this.lastMod;
    }

    public void setLastMod(Timestamp lastMod) {
        this.lastMod = lastMod;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MatchQuestion (");

        sb.append(matchId);
        sb.append(", ").append(num);
        sb.append(", ").append(unitId);
        sb.append(", ").append(questionMode);
        sb.append(", ").append(altIds);
        sb.append(", ").append(useraResult);
        sb.append(", ").append(userbResult);
        sb.append(", ").append(lastMod);

        sb.append(")");
        return sb.toString();
    }
}
