/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MatchAlt implements Serializable {

    private static final long serialVersionUID = 918086070;

    private String    unitId;
    private String    altId;
    private Integer   chosenCount;
    private Timestamp lastMod;

    public MatchAlt() {}

    public MatchAlt(MatchAlt value) {
        this.unitId = value.unitId;
        this.altId = value.altId;
        this.chosenCount = value.chosenCount;
        this.lastMod = value.lastMod;
    }

    public MatchAlt(
        String    unitId,
        String    altId,
        Integer   chosenCount,
        Timestamp lastMod
    ) {
        this.unitId = unitId;
        this.altId = altId;
        this.chosenCount = chosenCount;
        this.lastMod = lastMod;
    }

    public String getUnitId() {
        return this.unitId;
    }

    public void setUnitId(String unitId) {
        this.unitId = unitId;
    }

    public String getAltId() {
        return this.altId;
    }

    public void setAltId(String altId) {
        this.altId = altId;
    }

    public Integer getChosenCount() {
        return this.chosenCount;
    }

    public void setChosenCount(Integer chosenCount) {
        this.chosenCount = chosenCount;
    }

    public Timestamp getLastMod() {
        return this.lastMod;
    }

    public void setLastMod(Timestamp lastMod) {
        this.lastMod = lastMod;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MatchAlt (");

        sb.append(unitId);
        sb.append(", ").append(altId);
        sb.append(", ").append(chosenCount);
        sb.append(", ").append(lastMod);

        sb.append(")");
        return sb.toString();
    }
}
