/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Match implements Serializable {

    private static final long serialVersionUID = 290306141;

    private Integer   id;
    private Integer   langId;
    private Integer   state;
    private Integer   prizeId;
    private String    prizeIds;
    private Integer   createdBy;
    private Timestamp created;
    private Timestamp lastMod;

    public Match() {}

    public Match(Match value) {
        this.id = value.id;
        this.langId = value.langId;
        this.state = value.state;
        this.prizeId = value.prizeId;
        this.prizeIds = value.prizeIds;
        this.createdBy = value.createdBy;
        this.created = value.created;
        this.lastMod = value.lastMod;
    }

    public Match(
        Integer   id,
        Integer   langId,
        Integer   state,
        Integer   prizeId,
        String    prizeIds,
        Integer   createdBy,
        Timestamp created,
        Timestamp lastMod
    ) {
        this.id = id;
        this.langId = langId;
        this.state = state;
        this.prizeId = prizeId;
        this.prizeIds = prizeIds;
        this.createdBy = createdBy;
        this.created = created;
        this.lastMod = lastMod;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getLangId() {
        return this.langId;
    }

    public void setLangId(Integer langId) {
        this.langId = langId;
    }

    public Integer getState() {
        return this.state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Integer getPrizeId() {
        return this.prizeId;
    }

    public void setPrizeId(Integer prizeId) {
        this.prizeId = prizeId;
    }

    public String getPrizeIds() {
        return this.prizeIds;
    }

    public void setPrizeIds(String prizeIds) {
        this.prizeIds = prizeIds;
    }

    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    public Timestamp getLastMod() {
        return this.lastMod;
    }

    public void setLastMod(Timestamp lastMod) {
        this.lastMod = lastMod;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Match (");

        sb.append(id);
        sb.append(", ").append(langId);
        sb.append(", ").append(state);
        sb.append(", ").append(prizeId);
        sb.append(", ").append(prizeIds);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(created);
        sb.append(", ").append(lastMod);

        sb.append(")");
        return sb.toString();
    }
}
