/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Message implements Serializable {

    private static final long serialVersionUID = 780801221;

    private Integer   id;
    private Integer   userId;
    private Integer   type;
    private String    contents;
    private Timestamp created;

    public Message() {}

    public Message(Message value) {
        this.id = value.id;
        this.userId = value.userId;
        this.type = value.type;
        this.contents = value.contents;
        this.created = value.created;
    }

    public Message(
        Integer   id,
        Integer   userId,
        Integer   type,
        String    contents,
        Timestamp created
    ) {
        this.id = id;
        this.userId = userId;
        this.type = type;
        this.contents = contents;
        this.created = created;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getType() {
        return this.type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getContents() {
        return this.contents;
    }

    public void setContents(String contents) {
        this.contents = contents;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Message (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(type);
        sb.append(", ").append(contents);
        sb.append(", ").append(created);

        sb.append(")");
        return sb.toString();
    }
}
