/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Phrase implements Serializable {

    private static final long serialVersionUID = 845040510;

    private Integer   id;
    private Integer   enId;
    private Byte      langId;
    private String    display;
    private String    pronounce;
    private Byte      tokenCount;
    private String    tokenIds;
    private String    subIds;
    private String    audio;
    private String    audioId;
    private String    active;
    private String    reviewed;
    private Timestamp lastMod;

    public Phrase() {}

    public Phrase(Phrase value) {
        this.id = value.id;
        this.enId = value.enId;
        this.langId = value.langId;
        this.display = value.display;
        this.pronounce = value.pronounce;
        this.tokenCount = value.tokenCount;
        this.tokenIds = value.tokenIds;
        this.subIds = value.subIds;
        this.audio = value.audio;
        this.audioId = value.audioId;
        this.active = value.active;
        this.reviewed = value.reviewed;
        this.lastMod = value.lastMod;
    }

    public Phrase(
        Integer   id,
        Integer   enId,
        Byte      langId,
        String    display,
        String    pronounce,
        Byte      tokenCount,
        String    tokenIds,
        String    subIds,
        String    audio,
        String    audioId,
        String    active,
        String    reviewed,
        Timestamp lastMod
    ) {
        this.id = id;
        this.enId = enId;
        this.langId = langId;
        this.display = display;
        this.pronounce = pronounce;
        this.tokenCount = tokenCount;
        this.tokenIds = tokenIds;
        this.subIds = subIds;
        this.audio = audio;
        this.audioId = audioId;
        this.active = active;
        this.reviewed = reviewed;
        this.lastMod = lastMod;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getEnId() {
        return this.enId;
    }

    public void setEnId(Integer enId) {
        this.enId = enId;
    }

    public Byte getLangId() {
        return this.langId;
    }

    public void setLangId(Byte langId) {
        this.langId = langId;
    }

    public String getDisplay() {
        return this.display;
    }

    public void setDisplay(String display) {
        this.display = display;
    }

    public String getPronounce() {
        return this.pronounce;
    }

    public void setPronounce(String pronounce) {
        this.pronounce = pronounce;
    }

    public Byte getTokenCount() {
        return this.tokenCount;
    }

    public void setTokenCount(Byte tokenCount) {
        this.tokenCount = tokenCount;
    }

    public String getTokenIds() {
        return this.tokenIds;
    }

    public void setTokenIds(String tokenIds) {
        this.tokenIds = tokenIds;
    }

    public String getSubIds() {
        return this.subIds;
    }

    public void setSubIds(String subIds) {
        this.subIds = subIds;
    }

    public String getAudio() {
        return this.audio;
    }

    public void setAudio(String audio) {
        this.audio = audio;
    }

    public String getAudioId() {
        return this.audioId;
    }

    public void setAudioId(String audioId) {
        this.audioId = audioId;
    }

    public String getActive() {
        return this.active;
    }

    public void setActive(String active) {
        this.active = active;
    }

    public String getReviewed() {
        return this.reviewed;
    }

    public void setReviewed(String reviewed) {
        this.reviewed = reviewed;
    }

    public Timestamp getLastMod() {
        return this.lastMod;
    }

    public void setLastMod(Timestamp lastMod) {
        this.lastMod = lastMod;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Phrase (");

        sb.append(id);
        sb.append(", ").append(enId);
        sb.append(", ").append(langId);
        sb.append(", ").append(display);
        sb.append(", ").append(pronounce);
        sb.append(", ").append(tokenCount);
        sb.append(", ").append(tokenIds);
        sb.append(", ").append(subIds);
        sb.append(", ").append(audio);
        sb.append(", ").append(audioId);
        sb.append(", ").append(active);
        sb.append(", ").append(reviewed);
        sb.append(", ").append(lastMod);

        sb.append(")");
        return sb.toString();
    }
}
