/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Scene implements Serializable {

    private static final long serialVersionUID = -1714166424;

    private Integer   id;
    private Integer   townId;
    private Integer   phraseId;
    private String    desc;
    private String    filename;
    private Integer   nextSceneId;
    private String    active;
    private Timestamp lastMod;

    public Scene() {}

    public Scene(Scene value) {
        this.id = value.id;
        this.townId = value.townId;
        this.phraseId = value.phraseId;
        this.desc = value.desc;
        this.filename = value.filename;
        this.nextSceneId = value.nextSceneId;
        this.active = value.active;
        this.lastMod = value.lastMod;
    }

    public Scene(
        Integer   id,
        Integer   townId,
        Integer   phraseId,
        String    desc,
        String    filename,
        Integer   nextSceneId,
        String    active,
        Timestamp lastMod
    ) {
        this.id = id;
        this.townId = townId;
        this.phraseId = phraseId;
        this.desc = desc;
        this.filename = filename;
        this.nextSceneId = nextSceneId;
        this.active = active;
        this.lastMod = lastMod;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getTownId() {
        return this.townId;
    }

    public void setTownId(Integer townId) {
        this.townId = townId;
    }

    public Integer getPhraseId() {
        return this.phraseId;
    }

    public void setPhraseId(Integer phraseId) {
        this.phraseId = phraseId;
    }

    public String getDesc() {
        return this.desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public String getFilename() {
        return this.filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public Integer getNextSceneId() {
        return this.nextSceneId;
    }

    public void setNextSceneId(Integer nextSceneId) {
        this.nextSceneId = nextSceneId;
    }

    public String getActive() {
        return this.active;
    }

    public void setActive(String active) {
        this.active = active;
    }

    public Timestamp getLastMod() {
        return this.lastMod;
    }

    public void setLastMod(Timestamp lastMod) {
        this.lastMod = lastMod;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Scene (");

        sb.append(id);
        sb.append(", ").append(townId);
        sb.append(", ").append(phraseId);
        sb.append(", ").append(desc);
        sb.append(", ").append(filename);
        sb.append(", ").append(nextSceneId);
        sb.append(", ").append(active);
        sb.append(", ").append(lastMod);

        sb.append(")");
        return sb.toString();
    }
}
