/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SetPhrase implements Serializable {

    private static final long serialVersionUID = 422009611;

    private Integer   setId;
    private Integer   phraseId;
    private Timestamp lastMod;

    public SetPhrase() {}

    public SetPhrase(SetPhrase value) {
        this.setId = value.setId;
        this.phraseId = value.phraseId;
        this.lastMod = value.lastMod;
    }

    public SetPhrase(
        Integer   setId,
        Integer   phraseId,
        Timestamp lastMod
    ) {
        this.setId = setId;
        this.phraseId = phraseId;
        this.lastMod = lastMod;
    }

    public Integer getSetId() {
        return this.setId;
    }

    public void setSetId(Integer setId) {
        this.setId = setId;
    }

    public Integer getPhraseId() {
        return this.phraseId;
    }

    public void setPhraseId(Integer phraseId) {
        this.phraseId = phraseId;
    }

    public Timestamp getLastMod() {
        return this.lastMod;
    }

    public void setLastMod(Timestamp lastMod) {
        this.lastMod = lastMod;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SetPhrase (");

        sb.append(setId);
        sb.append(", ").append(phraseId);
        sb.append(", ").append(lastMod);

        sb.append(")");
        return sb.toString();
    }
}
