/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Spot implements Serializable {

    private static final long serialVersionUID = 1290676293;

    private Integer   id;
    private Integer   sceneId;
    private Integer   layer;
    private String    polygon;
    private String    polygonOpt;
    private Timestamp lastMod;
    private Integer   modBy;

    public Spot() {}

    public Spot(Spot value) {
        this.id = value.id;
        this.sceneId = value.sceneId;
        this.layer = value.layer;
        this.polygon = value.polygon;
        this.polygonOpt = value.polygonOpt;
        this.lastMod = value.lastMod;
        this.modBy = value.modBy;
    }

    public Spot(
        Integer   id,
        Integer   sceneId,
        Integer   layer,
        String    polygon,
        String    polygonOpt,
        Timestamp lastMod,
        Integer   modBy
    ) {
        this.id = id;
        this.sceneId = sceneId;
        this.layer = layer;
        this.polygon = polygon;
        this.polygonOpt = polygonOpt;
        this.lastMod = lastMod;
        this.modBy = modBy;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getSceneId() {
        return this.sceneId;
    }

    public void setSceneId(Integer sceneId) {
        this.sceneId = sceneId;
    }

    public Integer getLayer() {
        return this.layer;
    }

    public void setLayer(Integer layer) {
        this.layer = layer;
    }

    public String getPolygon() {
        return this.polygon;
    }

    public void setPolygon(String polygon) {
        this.polygon = polygon;
    }

    public String getPolygonOpt() {
        return this.polygonOpt;
    }

    public void setPolygonOpt(String polygonOpt) {
        this.polygonOpt = polygonOpt;
    }

    public Timestamp getLastMod() {
        return this.lastMod;
    }

    public void setLastMod(Timestamp lastMod) {
        this.lastMod = lastMod;
    }

    public Integer getModBy() {
        return this.modBy;
    }

    public void setModBy(Integer modBy) {
        this.modBy = modBy;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Spot (");

        sb.append(id);
        sb.append(", ").append(sceneId);
        sb.append(", ").append(layer);
        sb.append(", ").append(polygon);
        sb.append(", ").append(polygonOpt);
        sb.append(", ").append(lastMod);
        sb.append(", ").append(modBy);

        sb.append(")");
        return sb.toString();
    }
}
