/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSet implements Serializable {

    private static final long serialVersionUID = 2090581153;

    private Integer   setId;
    private Integer   langId;
    private Integer   userId;
    private Integer   count;
    private Timestamp lastMod;

    public UserSet() {}

    public UserSet(UserSet value) {
        this.setId = value.setId;
        this.langId = value.langId;
        this.userId = value.userId;
        this.count = value.count;
        this.lastMod = value.lastMod;
    }

    public UserSet(
        Integer   setId,
        Integer   langId,
        Integer   userId,
        Integer   count,
        Timestamp lastMod
    ) {
        this.setId = setId;
        this.langId = langId;
        this.userId = userId;
        this.count = count;
        this.lastMod = lastMod;
    }

    public Integer getSetId() {
        return this.setId;
    }

    public void setSetId(Integer setId) {
        this.setId = setId;
    }

    public Integer getLangId() {
        return this.langId;
    }

    public void setLangId(Integer langId) {
        this.langId = langId;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getCount() {
        return this.count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public Timestamp getLastMod() {
        return this.lastMod;
    }

    public void setLastMod(Timestamp lastMod) {
        this.lastMod = lastMod;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserSet (");

        sb.append(setId);
        sb.append(", ").append(langId);
        sb.append(", ").append(userId);
        sb.append(", ").append(count);
        sb.append(", ").append(lastMod);

        sb.append(")");
        return sb.toString();
    }
}
