/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserTown implements Serializable {

    private static final long serialVersionUID = 746474472;

    private Integer   userId;
    private Integer   townId;
    private String    full;
    private String    receipt;
    private Timestamp lastMod;

    public UserTown() {}

    public UserTown(UserTown value) {
        this.userId = value.userId;
        this.townId = value.townId;
        this.full = value.full;
        this.receipt = value.receipt;
        this.lastMod = value.lastMod;
    }

    public UserTown(
        Integer   userId,
        Integer   townId,
        String    full,
        String    receipt,
        Timestamp lastMod
    ) {
        this.userId = userId;
        this.townId = townId;
        this.full = full;
        this.receipt = receipt;
        this.lastMod = lastMod;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getTownId() {
        return this.townId;
    }

    public void setTownId(Integer townId) {
        this.townId = townId;
    }

    public String getFull() {
        return this.full;
    }

    public void setFull(String full) {
        this.full = full;
    }

    public String getReceipt() {
        return this.receipt;
    }

    public void setReceipt(String receipt) {
        this.receipt = receipt;
    }

    public Timestamp getLastMod() {
        return this.lastMod;
    }

    public void setLastMod(Timestamp lastMod) {
        this.lastMod = lastMod;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserTown (");

        sb.append(userId);
        sb.append(", ").append(townId);
        sb.append(", ").append(full);
        sb.append(", ").append(receipt);
        sb.append(", ").append(lastMod);

        sb.append(")");
        return sb.toString();
    }
}
