/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = -1597845870;

    private Integer   id;
    private String    nickname;
    private String    sessionId;
    private Integer   curSceneId;
    private Integer   curLangId;
    private String    robot;
    private String    macAddr;
    private String    deviceToken;
    private Timestamp lastLogin;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.nickname = value.nickname;
        this.sessionId = value.sessionId;
        this.curSceneId = value.curSceneId;
        this.curLangId = value.curLangId;
        this.robot = value.robot;
        this.macAddr = value.macAddr;
        this.deviceToken = value.deviceToken;
        this.lastLogin = value.lastLogin;
    }

    public User(
        Integer   id,
        String    nickname,
        String    sessionId,
        Integer   curSceneId,
        Integer   curLangId,
        String    robot,
        String    macAddr,
        String    deviceToken,
        Timestamp lastLogin
    ) {
        this.id = id;
        this.nickname = nickname;
        this.sessionId = sessionId;
        this.curSceneId = curSceneId;
        this.curLangId = curLangId;
        this.robot = robot;
        this.macAddr = macAddr;
        this.deviceToken = deviceToken;
        this.lastLogin = lastLogin;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNickname() {
        return this.nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getSessionId() {
        return this.sessionId;
    }

    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    public Integer getCurSceneId() {
        return this.curSceneId;
    }

    public void setCurSceneId(Integer curSceneId) {
        this.curSceneId = curSceneId;
    }

    public Integer getCurLangId() {
        return this.curLangId;
    }

    public void setCurLangId(Integer curLangId) {
        this.curLangId = curLangId;
    }

    public String getRobot() {
        return this.robot;
    }

    public void setRobot(String robot) {
        this.robot = robot;
    }

    public String getMacAddr() {
        return this.macAddr;
    }

    public void setMacAddr(String macAddr) {
        this.macAddr = macAddr;
    }

    public String getDeviceToken() {
        return this.deviceToken;
    }

    public void setDeviceToken(String deviceToken) {
        this.deviceToken = deviceToken;
    }

    public Timestamp getLastLogin() {
        return this.lastLogin;
    }

    public void setLastLogin(Timestamp lastLogin) {
        this.lastLogin = lastLogin;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(nickname);
        sb.append(", ").append(sessionId);
        sb.append(", ").append(curSceneId);
        sb.append(", ").append(curLangId);
        sb.append(", ").append(robot);
        sb.append(", ").append(macAddr);
        sb.append(", ").append(deviceToken);
        sb.append(", ").append(lastLogin);

        sb.append(")");
        return sb.toString();
    }
}
