/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserHistory implements Serializable {

    private static final long serialVersionUID = -671789682;

    private Integer   userId;
    private Integer   langId;
    private Integer   clueId;
    private Byte      result;
    private Timestamp lastMod;

    public UserHistory() {}

    public UserHistory(UserHistory value) {
        this.userId = value.userId;
        this.langId = value.langId;
        this.clueId = value.clueId;
        this.result = value.result;
        this.lastMod = value.lastMod;
    }

    public UserHistory(
        Integer   userId,
        Integer   langId,
        Integer   clueId,
        Byte      result,
        Timestamp lastMod
    ) {
        this.userId = userId;
        this.langId = langId;
        this.clueId = clueId;
        this.result = result;
        this.lastMod = lastMod;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getLangId() {
        return this.langId;
    }

    public void setLangId(Integer langId) {
        this.langId = langId;
    }

    public Integer getClueId() {
        return this.clueId;
    }

    public void setClueId(Integer clueId) {
        this.clueId = clueId;
    }

    public Byte getResult() {
        return this.result;
    }

    public void setResult(Byte result) {
        this.result = result;
    }

    public Timestamp getLastMod() {
        return this.lastMod;
    }

    public void setLastMod(Timestamp lastMod) {
        this.lastMod = lastMod;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserHistory (");

        sb.append(userId);
        sb.append(", ").append(langId);
        sb.append(", ").append(clueId);
        sb.append(", ").append(result);
        sb.append(", ").append(lastMod);

        sb.append(")");
        return sb.toString();
    }
}
