/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserClue implements Serializable {

    private static final long serialVersionUID = 1702338556;

    private Integer   userId;
    private Integer   langId;
    private Integer   clueId;
    private Integer   correctCount;
    private Integer   wrongCount;
    private Timestamp created;

    public UserClue() {}

    public UserClue(UserClue value) {
        this.userId = value.userId;
        this.langId = value.langId;
        this.clueId = value.clueId;
        this.correctCount = value.correctCount;
        this.wrongCount = value.wrongCount;
        this.created = value.created;
    }

    public UserClue(
        Integer   userId,
        Integer   langId,
        Integer   clueId,
        Integer   correctCount,
        Integer   wrongCount,
        Timestamp created
    ) {
        this.userId = userId;
        this.langId = langId;
        this.clueId = clueId;
        this.correctCount = correctCount;
        this.wrongCount = wrongCount;
        this.created = created;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getLangId() {
        return this.langId;
    }

    public void setLangId(Integer langId) {
        this.langId = langId;
    }

    public Integer getClueId() {
        return this.clueId;
    }

    public void setClueId(Integer clueId) {
        this.clueId = clueId;
    }

    public Integer getCorrectCount() {
        return this.correctCount;
    }

    public void setCorrectCount(Integer correctCount) {
        this.correctCount = correctCount;
    }

    public Integer getWrongCount() {
        return this.wrongCount;
    }

    public void setWrongCount(Integer wrongCount) {
        this.wrongCount = wrongCount;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserClue (");

        sb.append(userId);
        sb.append(", ").append(langId);
        sb.append(", ").append(clueId);
        sb.append(", ").append(correctCount);
        sb.append(", ").append(wrongCount);
        sb.append(", ").append(created);

        sb.append(")");
        return sb.toString();
    }
}
