/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.dev_tt.DevTt;
import org.jooq.dev_tt.Indexes;
import org.jooq.dev_tt.Keys;
import org.jooq.dev_tt.tables.records.ClueRankRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClueRank extends TableImpl<ClueRankRecord> {

    private static final long serialVersionUID = 758865698;

    /**
     * The reference instance of <code>dev_tt.clue_rank</code>
     */
    public static final ClueRank CLUE_RANK = new ClueRank();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClueRankRecord> getRecordType() {
        return ClueRankRecord.class;
    }

    /**
     * The column <code>dev_tt.clue_rank.clue_id</code>.
     */
    public final TableField<ClueRankRecord, Integer> CLUE_ID = createField("clue_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>dev_tt.clue_rank.lang_id</code>.
     */
    public final TableField<ClueRankRecord, Integer> LANG_ID = createField("lang_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>dev_tt.clue_rank.scene_id</code>.
     */
    public final TableField<ClueRankRecord, Integer> SCENE_ID = createField("scene_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>dev_tt.clue_rank.difficulty</code>.
     */
    public final TableField<ClueRankRecord, Integer> DIFFICULTY = createField("difficulty", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("3", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>dev_tt.clue_rank.rank</code>.
     */
    public final TableField<ClueRankRecord, Integer> RANK = createField("rank", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>dev_tt.clue_rank.right</code>.
     */
    public final TableField<ClueRankRecord, Integer> RIGHT = createField("right", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>dev_tt.clue_rank.wrong</code>.
     */
    public final TableField<ClueRankRecord, Integer> WRONG = createField("wrong", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>dev_tt.clue_rank.last_mod</code>.
     */
    public final TableField<ClueRankRecord, Timestamp> LAST_MOD = createField("last_mod", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0000-00-00 00:00:00", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>dev_tt.clue_rank</code> table reference
     */
    public ClueRank() {
        this(DSL.name("clue_rank"), null);
    }

    /**
     * Create an aliased <code>dev_tt.clue_rank</code> table reference
     */
    public ClueRank(String alias) {
        this(DSL.name(alias), CLUE_RANK);
    }

    /**
     * Create an aliased <code>dev_tt.clue_rank</code> table reference
     */
    public ClueRank(Name alias) {
        this(alias, CLUE_RANK);
    }

    private ClueRank(Name alias, Table<ClueRankRecord> aliased) {
        this(alias, aliased, null);
    }

    private ClueRank(Name alias, Table<ClueRankRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DevTt.DEV_TT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CLUE_RANK_CLUE_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ClueRankRecord>> getKeys() {
        return Arrays.<UniqueKey<ClueRankRecord>>asList(Keys.KEY_CLUE_RANK_CLUE_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClueRank as(String alias) {
        return new ClueRank(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClueRank as(Name alias) {
        return new ClueRank(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClueRank rename(String name) {
        return new ClueRank(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClueRank rename(Name name) {
        return new ClueRank(name, null);
    }
}
