/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.dev_tt.DevTt;
import org.jooq.dev_tt.Indexes;
import org.jooq.dev_tt.Keys;
import org.jooq.dev_tt.tables.records.LangRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Lang extends TableImpl<LangRecord> {

    private static final long serialVersionUID = -595915257;

    /**
     * The reference instance of <code>dev_tt.lang</code>
     */
    public static final Lang LANG = new Lang();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LangRecord> getRecordType() {
        return LangRecord.class;
    }

    /**
     * The column <code>dev_tt.lang.id</code>.
     */
    public final TableField<LangRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>dev_tt.lang.code</code>.
     */
    public final TableField<LangRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR(10).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>dev_tt.lang.desc</code>.
     */
    public final TableField<LangRecord, String> DESC = createField("desc", org.jooq.impl.SQLDataType.VARCHAR(60).nullable(false).defaultValue(org.jooq.impl.DSL.inline("n/a", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>dev_tt.lang.tokenize_type</code>.
     */
    public final TableField<LangRecord, Integer> TOKENIZE_TYPE = createField("tokenize_type", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>dev_tt.lang.last_mod</code>.
     */
    public final TableField<LangRecord, Timestamp> LAST_MOD = createField("last_mod", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>dev_tt.lang.mod_by</code>.
     */
    public final TableField<LangRecord, Integer> MOD_BY = createField("mod_by", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>dev_tt.lang</code> table reference
     */
    public Lang() {
        this(DSL.name("lang"), null);
    }

    /**
     * Create an aliased <code>dev_tt.lang</code> table reference
     */
    public Lang(String alias) {
        this(DSL.name(alias), LANG);
    }

    /**
     * Create an aliased <code>dev_tt.lang</code> table reference
     */
    public Lang(Name alias) {
        this(alias, LANG);
    }

    private Lang(Name alias, Table<LangRecord> aliased) {
        this(alias, aliased, null);
    }

    private Lang(Name alias, Table<LangRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DevTt.DEV_TT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.LANG_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<LangRecord, Integer> getIdentity() {
        return Keys.IDENTITY_LANG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<LangRecord> getPrimaryKey() {
        return Keys.KEY_LANG_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<LangRecord>> getKeys() {
        return Arrays.<UniqueKey<LangRecord>>asList(Keys.KEY_LANG_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Lang as(String alias) {
        return new Lang(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Lang as(Name alias) {
        return new Lang(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Lang rename(String name) {
        return new Lang(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lang rename(Name name) {
        return new Lang(name, null);
    }
}
