/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.dev_tt.DevTt;
import org.jooq.dev_tt.Indexes;
import org.jooq.dev_tt.Keys;
import org.jooq.dev_tt.tables.records.MatchAltRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MatchAlt extends TableImpl<MatchAltRecord> {

    private static final long serialVersionUID = -2144454432;

    /**
     * The reference instance of <code>dev_tt.match_alt</code>
     */
    public static final MatchAlt MATCH_ALT = new MatchAlt();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MatchAltRecord> getRecordType() {
        return MatchAltRecord.class;
    }

    /**
     * The column <code>dev_tt.match_alt.unit_id</code>.
     */
    public final TableField<MatchAltRecord, String> UNIT_ID = createField("unit_id", org.jooq.impl.SQLDataType.VARCHAR(25).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>dev_tt.match_alt.alt_id</code>.
     */
    public final TableField<MatchAltRecord, String> ALT_ID = createField("alt_id", org.jooq.impl.SQLDataType.VARCHAR(25).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>dev_tt.match_alt.chosen_count</code>.
     */
    public final TableField<MatchAltRecord, Integer> CHOSEN_COUNT = createField("chosen_count", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>dev_tt.match_alt.last_mod</code>.
     */
    public final TableField<MatchAltRecord, Timestamp> LAST_MOD = createField("last_mod", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>dev_tt.match_alt</code> table reference
     */
    public MatchAlt() {
        this(DSL.name("match_alt"), null);
    }

    /**
     * Create an aliased <code>dev_tt.match_alt</code> table reference
     */
    public MatchAlt(String alias) {
        this(DSL.name(alias), MATCH_ALT);
    }

    /**
     * Create an aliased <code>dev_tt.match_alt</code> table reference
     */
    public MatchAlt(Name alias) {
        this(alias, MATCH_ALT);
    }

    private MatchAlt(Name alias, Table<MatchAltRecord> aliased) {
        this(alias, aliased, null);
    }

    private MatchAlt(Name alias, Table<MatchAltRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DevTt.DEV_TT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.MATCH_ALT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MatchAltRecord> getPrimaryKey() {
        return Keys.KEY_MATCH_ALT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MatchAltRecord>> getKeys() {
        return Arrays.<UniqueKey<MatchAltRecord>>asList(Keys.KEY_MATCH_ALT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchAlt as(String alias) {
        return new MatchAlt(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchAlt as(Name alias) {
        return new MatchAlt(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MatchAlt rename(String name) {
        return new MatchAlt(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MatchAlt rename(Name name) {
        return new MatchAlt(name, null);
    }
}
