/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.dev_tt.DevTt;
import org.jooq.dev_tt.Indexes;
import org.jooq.dev_tt.tables.records.PhraseInfoRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PhraseInfo extends TableImpl<PhraseInfoRecord> {

    private static final long serialVersionUID = 581468018;

    /**
     * The reference instance of <code>dev_tt.phrase_info</code>
     */
    public static final PhraseInfo PHRASE_INFO = new PhraseInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PhraseInfoRecord> getRecordType() {
        return PhraseInfoRecord.class;
    }

    /**
     * The column <code>dev_tt.phrase_info.phrase_id</code>.
     */
    public final TableField<PhraseInfoRecord, Integer> PHRASE_ID = createField("phrase_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>dev_tt.phrase_info.scene_id</code>.
     */
    public final TableField<PhraseInfoRecord, Integer> SCENE_ID = createField("scene_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>dev_tt.phrase_info.type</code>.
     */
    public final TableField<PhraseInfoRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.CHAR(1).nullable(false), this, "");

    /**
     * The column <code>dev_tt.phrase_info.generation</code>.
     */
    public final TableField<PhraseInfoRecord, Integer> GENERATION = createField("generation", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>dev_tt.phrase_info.last_mod</code>.
     */
    public final TableField<PhraseInfoRecord, Timestamp> LAST_MOD = createField("last_mod", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>dev_tt.phrase_info</code> table reference
     */
    public PhraseInfo() {
        this(DSL.name("phrase_info"), null);
    }

    /**
     * Create an aliased <code>dev_tt.phrase_info</code> table reference
     */
    public PhraseInfo(String alias) {
        this(DSL.name(alias), PHRASE_INFO);
    }

    /**
     * Create an aliased <code>dev_tt.phrase_info</code> table reference
     */
    public PhraseInfo(Name alias) {
        this(alias, PHRASE_INFO);
    }

    private PhraseInfo(Name alias, Table<PhraseInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private PhraseInfo(Name alias, Table<PhraseInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DevTt.DEV_TT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PHRASE_INFO_PHRASE_IDX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhraseInfo as(String alias) {
        return new PhraseInfo(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PhraseInfo as(Name alias) {
        return new PhraseInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PhraseInfo rename(String name) {
        return new PhraseInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PhraseInfo rename(Name name) {
        return new PhraseInfo(name, null);
    }
}
