/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.dev_tt.DevTt;
import org.jooq.dev_tt.Indexes;
import org.jooq.dev_tt.Keys;
import org.jooq.dev_tt.tables.records.SetRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Set extends TableImpl<SetRecord> {

    private static final long serialVersionUID = 1776078147;

    /**
     * The reference instance of <code>dev_tt.set</code>
     */
    public static final Set SET = new Set();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SetRecord> getRecordType() {
        return SetRecord.class;
    }

    /**
     * The column <code>dev_tt.set.id</code>.
     */
    public final TableField<SetRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>dev_tt.set.town_id</code>.
     */
    public final TableField<SetRecord, Integer> TOWN_ID = createField("town_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("-1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>dev_tt.set.desc</code>.
     */
    public final TableField<SetRecord, String> DESC = createField("desc", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>dev_tt.set.size</code>.
     */
    public final TableField<SetRecord, Integer> SIZE = createField("size", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>dev_tt.set.phrase_id</code>.
     */
    public final TableField<SetRecord, Integer> PHRASE_ID = createField("phrase_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("-1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>dev_tt.set.active</code>.
     */
    public final TableField<SetRecord, String> ACTIVE = createField("active", org.jooq.impl.SQLDataType.CHAR(1).nullable(false).defaultValue(org.jooq.impl.DSL.inline("F", org.jooq.impl.SQLDataType.CHAR)), this, "");

    /**
     * The column <code>dev_tt.set.last_mod</code>.
     */
    public final TableField<SetRecord, Timestamp> LAST_MOD = createField("last_mod", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>dev_tt.set</code> table reference
     */
    public Set() {
        this(DSL.name("set"), null);
    }

    /**
     * Create an aliased <code>dev_tt.set</code> table reference
     */
    public Set(String alias) {
        this(DSL.name(alias), SET);
    }

    /**
     * Create an aliased <code>dev_tt.set</code> table reference
     */
    public Set(Name alias) {
        this(alias, SET);
    }

    private Set(Name alias, Table<SetRecord> aliased) {
        this(alias, aliased, null);
    }

    private Set(Name alias, Table<SetRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DevTt.DEV_TT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SET_ACTIVE_IDX, Indexes.SET_PHRASE_IDX, Indexes.SET_PRIMARY, Indexes.SET_TOWN_IDX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SetRecord> getPrimaryKey() {
        return Keys.KEY_SET_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SetRecord>> getKeys() {
        return Arrays.<UniqueKey<SetRecord>>asList(Keys.KEY_SET_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Set as(String alias) {
        return new Set(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Set as(Name alias) {
        return new Set(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Set rename(String name) {
        return new Set(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Set rename(Name name) {
        return new Set(name, null);
    }
}
