/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.dev_tt.DevTt;
import org.jooq.dev_tt.Indexes;
import org.jooq.dev_tt.Keys;
import org.jooq.dev_tt.tables.records.SetPhraseRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SetPhrase extends TableImpl<SetPhraseRecord> {

    private static final long serialVersionUID = -726035343;

    /**
     * The reference instance of <code>dev_tt.set_phrase</code>
     */
    public static final SetPhrase SET_PHRASE = new SetPhrase();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SetPhraseRecord> getRecordType() {
        return SetPhraseRecord.class;
    }

    /**
     * The column <code>dev_tt.set_phrase.set_id</code>.
     */
    public final TableField<SetPhraseRecord, Integer> SET_ID = createField("set_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>dev_tt.set_phrase.phrase_id</code>.
     */
    public final TableField<SetPhraseRecord, Integer> PHRASE_ID = createField("phrase_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>dev_tt.set_phrase.last_mod</code>.
     */
    public final TableField<SetPhraseRecord, Timestamp> LAST_MOD = createField("last_mod", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>dev_tt.set_phrase</code> table reference
     */
    public SetPhrase() {
        this(DSL.name("set_phrase"), null);
    }

    /**
     * Create an aliased <code>dev_tt.set_phrase</code> table reference
     */
    public SetPhrase(String alias) {
        this(DSL.name(alias), SET_PHRASE);
    }

    /**
     * Create an aliased <code>dev_tt.set_phrase</code> table reference
     */
    public SetPhrase(Name alias) {
        this(alias, SET_PHRASE);
    }

    private SetPhrase(Name alias, Table<SetPhraseRecord> aliased) {
        this(alias, aliased, null);
    }

    private SetPhrase(Name alias, Table<SetPhraseRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DevTt.DEV_TT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SET_PHRASE_PHRASE_IDX, Indexes.SET_PHRASE_PRIMARY, Indexes.SET_PHRASE_SET_IDX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SetPhraseRecord> getPrimaryKey() {
        return Keys.KEY_SET_PHRASE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SetPhraseRecord>> getKeys() {
        return Arrays.<UniqueKey<SetPhraseRecord>>asList(Keys.KEY_SET_PHRASE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SetPhrase as(String alias) {
        return new SetPhrase(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SetPhrase as(Name alias) {
        return new SetPhrase(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SetPhrase rename(String name) {
        return new SetPhrase(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SetPhrase rename(Name name) {
        return new SetPhrase(name, null);
    }
}
