/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.dev_tt.DevTt;
import org.jooq.dev_tt.Indexes;
import org.jooq.dev_tt.Keys;
import org.jooq.dev_tt.tables.records.UserTownRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserTown extends TableImpl<UserTownRecord> {

    private static final long serialVersionUID = -428533470;

    /**
     * The reference instance of <code>dev_tt.user_town</code>
     */
    public static final UserTown USER_TOWN = new UserTown();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserTownRecord> getRecordType() {
        return UserTownRecord.class;
    }

    /**
     * The column <code>dev_tt.user_town.user_id</code>.
     */
    public final TableField<UserTownRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>dev_tt.user_town.town_id</code>.
     */
    public final TableField<UserTownRecord, Integer> TOWN_ID = createField("town_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>dev_tt.user_town.full</code>.
     */
    public final TableField<UserTownRecord, String> FULL = createField("full", org.jooq.impl.SQLDataType.CHAR(1).nullable(false).defaultValue(org.jooq.impl.DSL.inline("F", org.jooq.impl.SQLDataType.CHAR)), this, "");

    /**
     * The column <code>dev_tt.user_town.receipt</code>.
     */
    public final TableField<UserTownRecord, String> RECEIPT = createField("receipt", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>dev_tt.user_town.last_mod</code>.
     */
    public final TableField<UserTownRecord, Timestamp> LAST_MOD = createField("last_mod", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>dev_tt.user_town</code> table reference
     */
    public UserTown() {
        this(DSL.name("user_town"), null);
    }

    /**
     * Create an aliased <code>dev_tt.user_town</code> table reference
     */
    public UserTown(String alias) {
        this(DSL.name(alias), USER_TOWN);
    }

    /**
     * Create an aliased <code>dev_tt.user_town</code> table reference
     */
    public UserTown(Name alias) {
        this(alias, USER_TOWN);
    }

    private UserTown(Name alias, Table<UserTownRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserTown(Name alias, Table<UserTownRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DevTt.DEV_TT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.USER_TOWN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserTownRecord> getPrimaryKey() {
        return Keys.KEY_USER_TOWN_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserTownRecord>> getKeys() {
        return Arrays.<UniqueKey<UserTownRecord>>asList(Keys.KEY_USER_TOWN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserTown as(String alias) {
        return new UserTown(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserTown as(Name alias) {
        return new UserTown(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserTown rename(String name) {
        return new UserTown(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserTown rename(Name name) {
        return new UserTown(name, null);
    }
}
