/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.dev_tt.DevTt;
import org.jooq.dev_tt.Indexes;
import org.jooq.dev_tt.Keys;
import org.jooq.dev_tt.tables.records.UserSetRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSet extends TableImpl<UserSetRecord> {

    private static final long serialVersionUID = -516519210;

    /**
     * The reference instance of <code>dev_tt.user_set</code>
     */
    public static final UserSet USER_SET = new UserSet();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserSetRecord> getRecordType() {
        return UserSetRecord.class;
    }

    /**
     * The column <code>dev_tt.user_set.set_id</code>.
     */
    public final TableField<UserSetRecord, Integer> SET_ID = createField("set_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>dev_tt.user_set.lang_id</code>.
     */
    public final TableField<UserSetRecord, Integer> LANG_ID = createField("lang_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>dev_tt.user_set.user_id</code>.
     */
    public final TableField<UserSetRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>dev_tt.user_set.count</code>.
     */
    public final TableField<UserSetRecord, Integer> COUNT = createField("count", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>dev_tt.user_set.last_mod</code>.
     */
    public final TableField<UserSetRecord, Timestamp> LAST_MOD = createField("last_mod", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>dev_tt.user_set</code> table reference
     */
    public UserSet() {
        this(DSL.name("user_set"), null);
    }

    /**
     * Create an aliased <code>dev_tt.user_set</code> table reference
     */
    public UserSet(String alias) {
        this(DSL.name(alias), USER_SET);
    }

    /**
     * Create an aliased <code>dev_tt.user_set</code> table reference
     */
    public UserSet(Name alias) {
        this(alias, USER_SET);
    }

    private UserSet(Name alias, Table<UserSetRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserSet(Name alias, Table<UserSetRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DevTt.DEV_TT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.USER_SET_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserSetRecord> getPrimaryKey() {
        return Keys.KEY_USER_SET_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserSetRecord>> getKeys() {
        return Arrays.<UniqueKey<UserSetRecord>>asList(Keys.KEY_USER_SET_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSet as(String alias) {
        return new UserSet(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSet as(Name alias) {
        return new UserSet(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserSet rename(String name) {
        return new UserSet(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserSet rename(Name name) {
        return new UserSet(name, null);
    }
}
