/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.dev_tt.tables.Clue;
import org.jooq.dev_tt.tables.records.ClueRecord;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClueDao extends DAOImpl<ClueRecord, org.jooq.dev_tt.tables.pojos.Clue, Integer> {

    /**
     * Create a new ClueDao without any configuration
     */
    public ClueDao() {
        super(Clue.CLUE, org.jooq.dev_tt.tables.pojos.Clue.class);
    }

    /**
     * Create a new ClueDao with an attached configuration
     */
    public ClueDao(Configuration configuration) {
        super(Clue.CLUE, org.jooq.dev_tt.tables.pojos.Clue.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(org.jooq.dev_tt.tables.pojos.Clue object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.Clue> fetchById(Integer... values) {
        return fetch(Clue.CLUE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.jooq.dev_tt.tables.pojos.Clue fetchOneById(Integer value) {
        return fetchOne(Clue.CLUE.ID, value);
    }

    /**
     * Fetch records that have <code>lang_id IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.Clue> fetchByLangId(Integer... values) {
        return fetch(Clue.CLUE.LANG_ID, values);
    }

    /**
     * Fetch records that have <code>scene_id IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.Clue> fetchBySceneId(Integer... values) {
        return fetch(Clue.CLUE.SCENE_ID, values);
    }

    /**
     * Fetch records that have <code>phrase_id IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.Clue> fetchByPhraseId(Integer... values) {
        return fetch(Clue.CLUE.PHRASE_ID, values);
    }

    /**
     * Fetch records that have <code>parent_id IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.Clue> fetchByParentId(Integer... values) {
        return fetch(Clue.CLUE.PARENT_ID, values);
    }

    /**
     * Fetch records that have <code>spot_ids IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.Clue> fetchBySpotIds(String... values) {
        return fetch(Clue.CLUE.SPOT_IDS, values);
    }

    /**
     * Fetch records that have <code>active IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.Clue> fetchByActive(String... values) {
        return fetch(Clue.CLUE.ACTIVE, values);
    }

    /**
     * Fetch records that have <code>reviewed IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.Clue> fetchByReviewed(String... values) {
        return fetch(Clue.CLUE.REVIEWED, values);
    }

    /**
     * Fetch records that have <code>last_mod IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.Clue> fetchByLastMod(Timestamp... values) {
        return fetch(Clue.CLUE.LAST_MOD, values);
    }
}
