/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.dev_tt.tables.Message;
import org.jooq.dev_tt.tables.records.MessageRecord;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MessageDao extends DAOImpl<MessageRecord, org.jooq.dev_tt.tables.pojos.Message, Integer> {

    /**
     * Create a new MessageDao without any configuration
     */
    public MessageDao() {
        super(Message.MESSAGE, org.jooq.dev_tt.tables.pojos.Message.class);
    }

    /**
     * Create a new MessageDao with an attached configuration
     */
    public MessageDao(Configuration configuration) {
        super(Message.MESSAGE, org.jooq.dev_tt.tables.pojos.Message.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(org.jooq.dev_tt.tables.pojos.Message object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.Message> fetchById(Integer... values) {
        return fetch(Message.MESSAGE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.jooq.dev_tt.tables.pojos.Message fetchOneById(Integer value) {
        return fetchOne(Message.MESSAGE.ID, value);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.Message> fetchByUserId(Integer... values) {
        return fetch(Message.MESSAGE.USER_ID, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.Message> fetchByType(Integer... values) {
        return fetch(Message.MESSAGE.TYPE, values);
    }

    /**
     * Fetch records that have <code>contents IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.Message> fetchByContents(String... values) {
        return fetch(Message.MESSAGE.CONTENTS, values);
    }

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.Message> fetchByCreated(Timestamp... values) {
        return fetch(Message.MESSAGE.CREATED, values);
    }
}
