/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.dev_tt.tables.Set;
import org.jooq.dev_tt.tables.records.SetRecord;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SetDao extends DAOImpl<SetRecord, org.jooq.dev_tt.tables.pojos.Set, Integer> {

    /**
     * Create a new SetDao without any configuration
     */
    public SetDao() {
        super(Set.SET, org.jooq.dev_tt.tables.pojos.Set.class);
    }

    /**
     * Create a new SetDao with an attached configuration
     */
    public SetDao(Configuration configuration) {
        super(Set.SET, org.jooq.dev_tt.tables.pojos.Set.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(org.jooq.dev_tt.tables.pojos.Set object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.Set> fetchById(Integer... values) {
        return fetch(Set.SET.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.jooq.dev_tt.tables.pojos.Set fetchOneById(Integer value) {
        return fetchOne(Set.SET.ID, value);
    }

    /**
     * Fetch records that have <code>town_id IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.Set> fetchByTownId(Integer... values) {
        return fetch(Set.SET.TOWN_ID, values);
    }

    /**
     * Fetch records that have <code>desc IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.Set> fetchByDesc(String... values) {
        return fetch(Set.SET.DESC, values);
    }

    /**
     * Fetch records that have <code>size IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.Set> fetchBySize(Integer... values) {
        return fetch(Set.SET.SIZE, values);
    }

    /**
     * Fetch records that have <code>phrase_id IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.Set> fetchByPhraseId(Integer... values) {
        return fetch(Set.SET.PHRASE_ID, values);
    }

    /**
     * Fetch records that have <code>active IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.Set> fetchByActive(String... values) {
        return fetch(Set.SET.ACTIVE, values);
    }

    /**
     * Fetch records that have <code>last_mod IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.Set> fetchByLastMod(Timestamp... values) {
        return fetch(Set.SET.LAST_MOD, values);
    }
}
