/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.dev_tt.tables.SetPhrase;
import org.jooq.dev_tt.tables.records.SetPhraseRecord;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SetPhraseDao extends DAOImpl<SetPhraseRecord, org.jooq.dev_tt.tables.pojos.SetPhrase, Record2<Integer, Integer>> {

    /**
     * Create a new SetPhraseDao without any configuration
     */
    public SetPhraseDao() {
        super(SetPhrase.SET_PHRASE, org.jooq.dev_tt.tables.pojos.SetPhrase.class);
    }

    /**
     * Create a new SetPhraseDao with an attached configuration
     */
    public SetPhraseDao(Configuration configuration) {
        super(SetPhrase.SET_PHRASE, org.jooq.dev_tt.tables.pojos.SetPhrase.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Integer, Integer> getId(org.jooq.dev_tt.tables.pojos.SetPhrase object) {
        return compositeKeyRecord(object.getSetId(), object.getPhraseId());
    }

    /**
     * Fetch records that have <code>set_id IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.SetPhrase> fetchBySetId(Integer... values) {
        return fetch(SetPhrase.SET_PHRASE.SET_ID, values);
    }

    /**
     * Fetch records that have <code>phrase_id IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.SetPhrase> fetchByPhraseId(Integer... values) {
        return fetch(SetPhrase.SET_PHRASE.PHRASE_ID, values);
    }

    /**
     * Fetch records that have <code>last_mod IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.SetPhrase> fetchByLastMod(Timestamp... values) {
        return fetch(SetPhrase.SET_PHRASE.LAST_MOD, values);
    }
}
