/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.dev_tt.tables.User;
import org.jooq.dev_tt.tables.records.UserRecord;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDao extends DAOImpl<UserRecord, org.jooq.dev_tt.tables.pojos.User, Integer> {

    /**
     * Create a new UserDao without any configuration
     */
    public UserDao() {
        super(User.USER, org.jooq.dev_tt.tables.pojos.User.class);
    }

    /**
     * Create a new UserDao with an attached configuration
     */
    public UserDao(Configuration configuration) {
        super(User.USER, org.jooq.dev_tt.tables.pojos.User.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(org.jooq.dev_tt.tables.pojos.User object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.User> fetchById(Integer... values) {
        return fetch(User.USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public org.jooq.dev_tt.tables.pojos.User fetchOneById(Integer value) {
        return fetchOne(User.USER.ID, value);
    }

    /**
     * Fetch records that have <code>nickname IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.User> fetchByNickname(String... values) {
        return fetch(User.USER.NICKNAME, values);
    }

    /**
     * Fetch records that have <code>session_id IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.User> fetchBySessionId(String... values) {
        return fetch(User.USER.SESSION_ID, values);
    }

    /**
     * Fetch records that have <code>cur_scene_id IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.User> fetchByCurSceneId(Integer... values) {
        return fetch(User.USER.CUR_SCENE_ID, values);
    }

    /**
     * Fetch records that have <code>cur_lang_id IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.User> fetchByCurLangId(Integer... values) {
        return fetch(User.USER.CUR_LANG_ID, values);
    }

    /**
     * Fetch records that have <code>robot IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.User> fetchByRobot(String... values) {
        return fetch(User.USER.ROBOT, values);
    }

    /**
     * Fetch records that have <code>mac_addr IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.User> fetchByMacAddr(String... values) {
        return fetch(User.USER.MAC_ADDR, values);
    }

    /**
     * Fetch records that have <code>device_token IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.User> fetchByDeviceToken(String... values) {
        return fetch(User.USER.DEVICE_TOKEN, values);
    }

    /**
     * Fetch records that have <code>last_login IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.User> fetchByLastLogin(Timestamp... values) {
        return fetch(User.USER.LAST_LOGIN, values);
    }
}
