/*
 * This file is generated by jOOQ.
*/
package org.jooq.dev_tt.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.dev_tt.tables.UserTown;
import org.jooq.dev_tt.tables.records.UserTownRecord;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserTownDao extends DAOImpl<UserTownRecord, org.jooq.dev_tt.tables.pojos.UserTown, Record2<Integer, Integer>> {

    /**
     * Create a new UserTownDao without any configuration
     */
    public UserTownDao() {
        super(UserTown.USER_TOWN, org.jooq.dev_tt.tables.pojos.UserTown.class);
    }

    /**
     * Create a new UserTownDao with an attached configuration
     */
    public UserTownDao(Configuration configuration) {
        super(UserTown.USER_TOWN, org.jooq.dev_tt.tables.pojos.UserTown.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Integer, Integer> getId(org.jooq.dev_tt.tables.pojos.UserTown object) {
        return compositeKeyRecord(object.getUserId(), object.getTownId());
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.UserTown> fetchByUserId(Integer... values) {
        return fetch(UserTown.USER_TOWN.USER_ID, values);
    }

    /**
     * Fetch records that have <code>town_id IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.UserTown> fetchByTownId(Integer... values) {
        return fetch(UserTown.USER_TOWN.TOWN_ID, values);
    }

    /**
     * Fetch records that have <code>full IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.UserTown> fetchByFull(String... values) {
        return fetch(UserTown.USER_TOWN.FULL, values);
    }

    /**
     * Fetch records that have <code>receipt IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.UserTown> fetchByReceipt(String... values) {
        return fetch(UserTown.USER_TOWN.RECEIPT, values);
    }

    /**
     * Fetch records that have <code>last_mod IN (values)</code>
     */
    public List<org.jooq.dev_tt.tables.pojos.UserTown> fetchByLastMod(Timestamp... values) {
        return fetch(UserTown.USER_TOWN.LAST_MOD, values);
    }
}
